import {readJSON,writeJSON} from './story-state.js?v=2';
export class AudioManager{
 constructor(){this.ctx=null;this.mode='menu';this.next=0;this.beat=0;this.scheduled=0;this.nodes=new Set();const s=readJSON('school-audio-v2',{});this.enabled=s.enabled!==false;this.levels={master:.65,bgm:.55,sfx:.65};for(const k of Object.keys(this.levels))if(Number.isFinite(s[k]))this.levels[k]=Math.max(0,Math.min(1,s[k]));}
 async unlock(){try{if(!this.ctx){this.ctx=new(window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.music=this.ctx.createGain();this.effects=this.ctx.createGain();this.music.connect(this.master);this.effects.connect(this.master);this.master.connect(this.ctx.destination);this.apply();}if(this.ctx.state==='suspended')await this.ctx.resume();this.tick();}catch{}}
 apply(){if(this.ctx){this.master.gain.value=this.levels.master;this.music.gain.value=this.enabled?this.levels.bgm:0;this.effects.gain.value=this.enabled?this.levels.sfx:0;}writeJSON('school-audio-v2',{enabled:this.enabled,...this.levels});}
 toggle(){this.enabled=!this.enabled;this.apply();this.unlock();return this.enabled;}
 setMode(mode){if(mode===this.mode)return;this.mode=mode;this.beat=0;this.next=0;for(const n of this.nodes){try{n.stop()}catch{}}this.nodes.clear();}
 tone(freq,when,duration,volume,type='sine',channel='music'){if(!this.ctx)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.0001,when);g.gain.linearRampToValueAtTime(volume,when+Math.min(.1,duration*.15));g.gain.exponentialRampToValueAtTime(.0001,when+duration);o.connect(g);g.connect(channel==='music'?this.music:this.effects);o.start(when);o.stop(when+duration+.03);this.nodes.add(o);o.onended=()=>{this.nodes.delete(o);o.disconnect();g.disconnect()};this.scheduled++;}
 sfx(freq=440,duration=.12,volume=.05,type='sine'){if(this.ctx?.state==='running'&&this.enabled)this.tone(freq,this.ctx.currentTime,duration,Math.min(.22,volume*2),type,'effects');}
 tick(){if(!this.enabled||this.ctx?.state!=='running'||document.hidden)return;const now=this.ctx.currentTime;if(this.next>now+.15)return;const sets={menu:[196,233.08,293.66,220,174.61,261.63,233.08,196],school:[98,146.83,116.54,130.81,98,155.56,110,130.81],sad:[261.63,329.63,392,329.63,220,293.66,349.23,293.66],hidden:[65.41,98,69.30,92.50,61.74,87.31,65.41,103.83],hope:[261.63,329.63,392,523.25,293.66,349.23,440,392],combat:[110,164.81,110,174.61,98,146.83,123.47,164.81]};const notes=sets[this.mode]||sets.school;const when=Math.max(now+.02,this.next);const interval=this.mode==='combat'?.38:.72;this.tone(notes[this.beat%notes.length],when,interval*1.5,.12,this.mode==='hidden'?'sine':'triangle');if(this.beat%4===0){this.tone(notes[0]/2,when,interval*4.2,.15);this.tone(notes[2]/2,when,interval*4,.065);}this.beat++;this.next=when+interval;}
 snapshot(){return {enabled:this.enabled,mode:this.mode,context:this.ctx?.state||'not-started',scheduled:this.scheduled,levels:{...this.levels}};}
}
