import {ART,STAGES,ROUTE_STATS,ITEM_NAMES,freshStory,normalizeStory,normalizeAchievements,readJSON,writeJSON,escapeHTML as h,safeName} from './story-state.js?v=2';
import {createStoryUI} from './story-ui.js?v=2';
import {DEFAULT_AVATAR,avatarSVG} from './avatar.js?v=2';
import {blocked,stairPlatforms,groundAt} from './physics.js?v=2';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const TITLES={easy_hall:'급식동 · 돌아오지 않은 점심',easy_cafe:'급식실 · 얼굴 없는 영양사',easy_toilet:'화장실 · 세면대의 열쇠',normal_hall:'본관 · 이름을 부르는 강아지',normal_office:'교장실 · 세 개의 그림자',normal_science:'과학실 · 기억을 만드는 법',hard_entry:'신관 · 세 머리의 문지기',hard_english:'1층 · 두려움을 말하는 법',hard_stairs:'부서진 계단 · 두 번의 도약',hard_math:'2층 · 진짜와 가짜',hard_gym:'3층 · 원형 인장의 주인',hard_maze:'잊힌 복도 · 삼각형의 길',hard_roof:'옥상 · 아직 듣고 있어',hard_final:'마지막 계단 · 현실로'};
export function createCampaign(e){
 let data=freshStory(),achievements=normalizeAchievements(readJSON('school-achievements-v2',{}));
 let enemies=[],companions=[],bounds={minX:-24,maxX:24,minZ:-24,maxZ:28},attackCD=0,hitCD=0,friendCD=0,hiddenFor=0,climbTime=60,ending=false,miniFails=0;
 const ui=createStoryUI(e);const flags=()=>data.flags;const has=i=>data.items.includes(i);const add=i=>{if(!has(i))data.items.push(i)};const remove=i=>data.items=data.items.filter(x=>x!==i);
 function checkpoint(){e.saveProgress();hud();}
 function log(text){if(!data.journal.includes(text)){data.journal.push(text);data.journal=data.journal.slice(-40)}checkpoint();}
 function finishFlag(key,message){flags()[key]=true;if(message)log(message);checkpoint();}
 function close(){e.closeModal();}
 function go(stage,message){e.loadStage(stage);if(message)ui.dialogue(message[0],message[1],message[2]||[['직접 살펴보기',close]],message[3]||{});}
 function refresh(){const p={...e.player};e.loadStage(e.state.stage);e.spawn(p.x,p.y,p.z,p.yaw);checkpoint();}
 function speak(name,text,choices,opts){ui.dialogue(name,text,choices,opts)}
 function own(stage){return STAGES.includes(stage)}
 function startFresh(){data=freshStory();ending=false;enemies=[];companions=[];miniFails=0;}
 function intro(){e.audio.setMode('school');speak(safeName(e.avatar.name,'나'),['마지막으로 기억나는 것은 네 번 울리던 종소리였다. 눈을 뜨니 폐교된 학교 정문 앞. 손에는 누가 쥐여 주었는지 모를 황동 열쇠가 남아 있었다.','스피커에서 낮은 목소리가 흘러나온다. “아직 이곳에 남은 이름들을 찾아 줘. 네가 외면했던 밤을 기억할 수 있다면… 문도 열릴 거야.”','왼쪽 급식실에는 끝나지 않은 점심이, 본관에는 조각난 기억이, 신관 옥상에는 마지막 목소리가 남아 있다. 먼저 정문의 숫자 자물쇠를 살펴보자.'],[['교문 앞으로 걸어가기',close]],{kicker:'PROLOGUE · 네 번의 종소리',portrait:avatarSVG(e.avatar)});}
 function enter(route){data.active=true;ending=false;e.state.route=route;const st=ROUTE_STATS[route];Object.assign(data,{hp:st.hp,maxHp:st.hp,lives:st.lives,attack:data.weapon==='전설의 검'?90:st.attack,armor:100});for(const i of ['flashlight','armor','commonKey'])add(i);e.state.light=true;e.state.notes=[];e.state.key=false;
  if(route==='easy')go('easy_hall',['학교 방송',['“오늘도, 배고픈 아이가 없도록.” 낡은 방송이 같은 문장을 반복한다. 오른쪽은 급식실, 왼쪽은 화장실이다.','목에 걸린 수호의 지팡이가 빛난다. Q로 공격할 수 있지만, 모든 귀신을 공격해서 해결할 수 있는 것은 아니다.']]);
  else if(route==='normal'){go('normal_hall');if(!data.dogName)nameCompanion('dog');else speak(data.dogName,'갈색 말티푸가 꼬리를 흔든다. 코끝은 관리인이 든 열쇠 꾸러미를 향한다. “멍!”',[['함께 들어가기',close]],{portrait:dogPortrait()});}
  else go('hard_entry',['세 머리의 문지기','“말로 지나갈 것인가, 힘으로 지나갈 것인가.” 세 개의 머리가 각기 다른 목소리로 묻는다. 60초 안에 세 질문을 풀면 문이 열린다.']);checkpoint();
 }
 function nameCompanion(kind){const dog=kind==='dog';e.showModal('naming',`<div class="modal-eyebrow">${dog?'A SMALL GUIDE':'A NEW FRIEND'}</div><h2 id="modal-title">${dog?'작은 안내견의 이름':'이제 너를 이름으로 부를게'}</h2><p>${dog?'갈색 말티푸가 손등을 살짝 핥았다. 이 밤을 함께 걸어 줄 친구에게 이름을 지어 주세요.':'학생이 살아 있는 사람의 모습으로 돌아왔다. 앞으로 함께할 친구의 이름을 지어 주세요.'}</p><form id="name-form"><label for="companion-name">${dog?'강아지':'친구'} 이름</label><input id="companion-name" class="story-input" maxlength="16" value="${h(dog?(data.dogName||'모카'):(data.friendName||'하루'))}" autocomplete="off"><button class="primary" type="submit">함께 걷기 →</button></form>`);$('#name-form').onsubmit=ev=>{ev.preventDefault();const name=safeName($('#companion-name').value,dog?'모카':'하루');if(dog){data.dogName=name;close();refresh();log(`${name}: 황동 열쇠를 관리인에게 건네자. 막히면 H로 강아지의 힌트를 들을 수 있다.`);e.toast(name+'와 함께합니다. H · 힌트');}else{data.friendName=name;data.friendGender=e.avatar.gender==='girl'?'boy':'girl';flags().normal_friend=true;close();refresh();log(`${name}: 내 이야기를 끝까지 들어 준 사람. 신관 끝까지 함께 가기로 약속했다.`);}};$('#companion-name').focus();}
 function dogPortrait(){return '<svg viewBox="0 0 180 180" aria-label="갈색 말티푸 안내견"><ellipse cx="90" cy="111" rx="57" ry="48" fill="#b58b62"/><ellipse cx="46" cy="73" rx="22" ry="43" fill="#79563f"/><ellipse cx="135" cy="73" rx="22" ry="43" fill="#79563f"/><circle cx="90" cy="74" r="48" fill="#cba375"/><circle cx="72" cy="72" r="6" fill="#292331"/><circle cx="109" cy="72" r="6" fill="#292331"/><ellipse cx="90" cy="91" rx="13" ry="10" fill="#3a2d2c"/><path d="M78 110q12 13 25 0" fill="none" stroke="#634532" stroke-width="4"/><path d="M68 127h46v14H68z" fill="#6d9e9d"/></svg>';}
 function shell(title,w=14,d=28,color='#58636e'){e.resetScene();enemies=[];companions=[];hitCD=1;bounds={minX:-w/2+.45,maxX:w/2-.45,minZ:-20+.45,maxZ:7-.45};e.floorRect(0,-6.5,w,27,0,color);e.wall(-w/2,-6.5,.25,27,4.5);e.wall(w/2,-6.5,.25,27,4.5);e.wall(0,-20,w,.25,4.5);e.wall(0,7,w,.25,4.5);e.box(0,4.55,-6.5,w,.15,27,'#384651');for(let z=3;z>-19;z-=6){e.lamp(0,4.4,z);for(const x of [-w/2+.15,w/2-.15]){e.box(x,2.45,z,.06,1.45,2.1,'#4c657c');e.box(x,2.45,z,.07,.045,2.1,'#2b394a');}}e.sign(title,0,3.55,-19.8,5,'#d2dbc6','#29474c');e.audio.setMode('school');}
 function door(id,label,x,z,stage,condition=()=>true,message){e.box(x,1.4,z,1.8,2.8,.1,'#355b60');e.sign(label,x,3.1,z+.12,2.8,'#b8e9da','#2a4b52');e.marker(x,2.05,z+.4);e.interact(id,label,x,z+.6,()=>{if(condition())go(stage,message)},2.35);}
 function back(stage){door('back','복도로 돌아가기',0,6.68,stage);}
 function pickup(id,label,x,z,condition=()=>true,onTake){if(has(id))return;const m=e.marker(x,1.1,z,'#e4cf96');e.box(x,.45,z,.6,.9,.6,'#52606b');e.interact(id,label+' 줍기',x,z,()=>{if(has(id)){e.toast('이미 챙겼습니다.');return}if(!condition())return;add(id);m.visible=false;log(label+' 획득');e.sound(800,.12,.025);e.toast(label+'을 챙겼어요.');onTake?.();},2.05);}
 function npc(name,x,z,action,look={}){const model=e.createCharacter({...DEFAULT_AVATAR,...look});model.position.set(x,0,z);model.rotation.y=Math.PI;e.world.add(model);const label=e.sign(name,x,2.35,z+.05,2,'#d9dacb','#344757');e.interact(name,name+'에게 말 걸기',x,z+.4,action,2.6);return model;}
 function enemy(id,name,x,z,opts={}){if(flags()['dead_'+id])return null;const model=opts.character?e.createCharacter({...DEFAULT_AVATAR,...opts.character}):e.createGhost();model.position.set(x,0,z);e.world.add(model);const label=e.sign(name,0,0,0,2.3,'#ffd2d4','#402e44');model.add(label);label.position.set(0,2.9,0);const mob={id,name,model,hp:opts.hp||130,maxHp:opts.hp||130,speed:opts.speed||ROUTE_STATS[e.state.route].speed,cooldown:.7,windup:0,stun:0,immortal:!!opts.immortal,passive:!!opts.passive,opts,label};enemies.push(mob);return mob;}
 function dogModel(){const g=new e.THREE.Group();e.sphere(0,.4,0,.3,'#af835a',g,1,1,1.6);e.sphere(0,.68,-.26,.29,'#c29a70',g);for(const x of [-.26,.26])e.sphere(x,.61,-.23,.16,'#7f5a41',g,.7,1.55,.8);for(const x of [-.15,.15])for(const z of [-.23,.27])e.box(x,.16,z,.105,.3,.13,'#b18b62',false,g);e.sphere(0,.63,-.52,.072,'#2a2831',g);for(const x of [-.11,.11])e.sphere(x,.76,-.5,.035,'#242231',g,1,1,1,true);const tail=e.sphere(0,.58,.45,.12,'#ad7e56',g,.7,1.8,.7);tail.rotation.x=.4;return g;}
 function addCompanions(){if(!data.active)return;if(data.dogName&&e.state.route!=='easy'){const g=dogModel();g.position.set(1,0,3);e.world.add(g);companions.push({kind:'dog',model:g,offset:1.05,name:data.dogName})}if(data.friendName&&e.state.route!=='easy'){const g=e.createCharacter({...DEFAULT_AVATAR,gender:data.friendGender,style:data.friendGender==='boy'?'short':'long',hair:'#665043',outfit:'#71958c'});g.position.set(-1.2,0,3);e.world.add(g);companions.push({kind:'friend',model:g,offset:-1.2,name:data.friendName})}}
 function build(stage){ending=false;if(stage==='hard_stairs')return buildStoryStairs();if(stage==='hard_final')return buildFinal();shell(TITLES[stage]||'잊힌 교실',stage==='normal_office'?16:14);const F=flags();
  if(stage==='easy_hall'){
   back('gate');door('cafe-door',F.easy_cafeSolved?'잠긴 급식실':'급식실',5,-8,'easy_cafe',()=>{if(F.easy_cafeSolved){e.toast(has('commonKey')?'열쇠가 구멍에 맞지 않아.':'잠겨있어.');return false}return true},['얼굴 없는 영양사','그녀는 무기를 보고도 물러서지 않았다. 식판 위에 남겨진 세 장의 기록이 희미하게 빛난다. “아이들은… 점심을 먹었나요?”']);
   door('toilet-door','화장실',-5,-8,'easy_toilet',()=>{if(!F.easy_cafeSolved){e.toast('영양사의 이야기가 끝나기 전에는 문이 열리지 않는다.');return false}return true});
   for(const z of [-15,-6,3])e.box(-6.79,2,z,.05,1.6,1.9,'#748195');e.interact('hidden-window','빛이 다르게 비치는 창문 조사',-6.1,3,()=>speak('거울 속 나','창문 속 얼굴이 내 움직임보다 반 박자 늦게 웃었다.',[['유리에 손을 댄다',hiddenEnding],['천천히 물러난다',close]],{portrait:avatarSVG({...e.avatar,mouth:'smile'}),kicker:'THE THIRD WINDOW'}),1.8);
   if(F.easy_cafeSolved){door('easy-exit','새로 생긴 문',0,-19.75,'gate',()=>{if(!has('toiletKey')){e.toast('새 문의 열쇠는 화장실 세면대에 남아 있다.');return false}chapterClear('easy');return false});}
  }
  if(stage==='easy_cafe'){
   back('easy_hall');for(const x of [-3.8,3.8])for(const z of [-3,-10]){e.box(x,.8,z,2.8,.18,1.6,'#b7a98d',true);e.box(x,.46,z+1.3,2.7,.18,.5,'#7c817c',true)}
   const memories=[['첫 번째 식판','급식비를 내지 못한 아이의 이름 옆에, 작은 글씨가 남아 있다. “내 몫으로 주세요.”'],['두 번째 식판','학부모 항의서 뒤로 낡은 식단표가 나온다. 영양사는 아픈 아이에게 다른 식사를 챙겼지만, 아무도 그녀의 말을 끝까지 듣지 않았다.'],['세 번째 식판','마지막 방송 원고. “잘못된 소문 말고, 아이들의 이름을 기억해 주세요. 저는 오늘도… 점심을 준비했습니다.”']];
   [[-3.8,-3],[3.8,-3],[-3.8,-10]].forEach(([x,z],i)=>{if(F['easy_memory'+i])return;const m=e.marker(x,1.35,z);e.interact('memory-'+i,memories[i][0]+' 조사',x,z,()=>{if(!F['easy_memory'+i]){F['easy_memory'+i]=true;m.visible=false;log(memories[i][1])}speak('남겨진 기록',memories[i][1]);},2.3)});
   enemy('nutritionist','얼굴 없는 영양사',1,-14,{immortal:true,passive:true,speed:.9,onHit:()=>{hiddenFor=0;e.toast('무기가 통하지 않는다. 식판의 기록을 찾거나 찬장 뒤에 숨자.');}});
   e.box(5.4,1.4,2,1.1,2.8,1,'#485661',true);e.interact('pantry-hide','찬장 뒤에 숨기',4.6,2,()=>{hiddenFor=8;enemies.forEach(m=>m.passive=true);e.toast('숨을 낮췄다. 영양사의 발소리가 멀어진다.');},2);
   e.sign('오늘도, 배고픈 아이가 없도록.',0,2.5,-19.7,5);e.interact('nutritionist-memory','영양사의 과거 보기',0,-17.8,()=>{if(![0,1,2].every(i=>F['easy_memory'+i])){e.toast('세 식판의 기록을 먼저 읽어 보자.');return}speak('영양사의 기억',['그녀가 지키고 싶었던 것은 식단표의 숫자가 아니라, 매일 같은 자리에 앉던 아이들의 이름이었다.','“누군가 한 번만 내 이야기를 들어 주었다면.” 얼굴 없는 영양사가 텅 빈 식판을 내려다본다.'],[['아이들의 이름을 함께 기억하겠다고 말한다',()=>{finishFlag('easy_cafeSolved','영양사의 이야기를 들었다. 그녀는 빈 식판을 내려놓고, 더는 돌아오지 않을 점심에서 벗어났다.');go('easy_hall');e.toast('급식실 문이 조용히 잠겼다. 화장실에서 출구의 열쇠를 찾자.');}],['잠시 생각한다',close]]);},2.8);
  }
  if(stage==='easy_toilet'){
   back('easy_hall');for(const x of [-4,0,4]){e.box(x,.37,-6,1,.74,1.2,'#c0cbc5',true);e.cylinder(x,.8,-6,.48,.4,.18,'#d6dacf');e.box(x,1,-6.6,.9,1.8,.4,'#b3c4c2',true)}
   e.interact('toilet','가운데 변기 조사',0,-4.5,()=>{if(F.easy_toiletAwake){e.toast('세면대 쪽에 희미한 빛이 보인다.');return}F.easy_toiletAwake=true;e.sphere(0,1.25,-5.6,.17,'#b5bac5',e.world,.55,2.4,.6);e.sound(100,.35,.07);if(!e.state.comfort)e.damageFlash();speak('물 아래의 목소리','차가운 손이 물 위로 솟았다. “문을 열어 줘… 나도, 밖으로 나가고 싶어.” 뒤엉킨 원혼을 수호의 지팡이로 진정시켜야 한다.',[['뒤로 물러나 맞선다',()=>{close();refresh()}]]);},2.1);
   if(F.easy_toiletAwake&&!F.dead_toilet)enemy('toilet','화장실의 원혼',0,-10,{hp:120,speed:1.1,onDeath:()=>{log('화장실 원혼을 진정시켰다. 세면대에 열쇠가 나타났다.');refresh();}});
   e.box(0,.85,-17.2,3,.25,1.1,'#a1c0c1',true);pickup('toiletKey','세면대 열쇠',0,-16,()=>{if(!F.dead_toilet){e.toast('원혼을 진정시켜야 열쇠를 꺼낼 수 있다.');return false}return true});
  }
  if(stage==='normal_hall'){
   back('gate');if(!F.normal_guard)npc('관리인',0,-2,()=>speak('관리인','“아이들을 두고 문을 잠글 수는 없지… 그 황동 열쇠, 돌려주겠니?”',[['황동 열쇠를 건넨다',()=>{if(!has('commonKey')){e.toast('정문에서 가져온 황동 열쇠가 필요하다.');return}remove('commonKey');finishFlag('normal_guard','관리인에게 열쇠를 돌려주었다. 교장실과 과학실의 위치를 알려 주었다.');close();refresh();}],['조금 더 살펴본다',close]],{gender:'boy',hair:'#80858c'}),{gender:'boy',style:'short',hair:'#7a7b82',outfit:'#585d67'});
   const guard=()=>{if(!F.normal_guard){e.toast('먼저 관리인에게 황동 열쇠를 건네자.');return false}return true};
   door('office-door','교장실',5,-9,'normal_office',guard,['교장실의 세 그림자','교장, 교감, 반장의 그림자가 동시에 일어섰다. “기록을 가져가게 둘 순 없어.” Q로 공격하고, WASD로 공격 범위를 벗어나세요.']);
   door('science-door','과학실',-5,-9,'normal_science',()=>{if(!guard())return false;if(!has('scienceKey')){e.toast('과학실 열쇠는 교장실의 세 그림자가 지키고 있다.');return false}return true});
   door('normal-exit','빛이 새어 나오는 문',0,-19.75,'chase',()=>{if(!has('goldenKey')){e.toast('과학실에서 세 조각을 모아 황금 열쇠를 만들어야 한다.');return false}if(!data.friendName){kongDialogue();return false}F.normal_chase=true;e.state.route='normal';log('황금 열쇠로 문을 열었다. 친구와 함께 마지막 복도를 달려야 한다.');return true},['함께 달리는 발소리','등 뒤에서 다른 발소리가 따라붙는다. Shift로 달리며 장애물을 피하고, 복도 끝 출구에서 E를 누르자.']);
  }
  if(stage==='normal_office'){
   back('normal_hall');for(const x of [-5,5])e.box(x,.8,-7,2.2,1.6,2,'#8c796c',true);
   [['principal','교장 귀신',-3,-9],['vice','교감 귀신',3,-10],['leader','반장 학생 귀신',0,-13]].forEach(([id,name,x,z])=>enemy(id,name,x,z,{hp:110,speed:1.5,onDeath:()=>{if(['principal','vice','leader'].every(id=>F['dead_'+id])){add('scienceKey');finishFlag('normal_office','세 그림자가 물러났다. 숨겨진 과학실 열쇠를 찾았다.');e.toast('과학실 열쇠 획득 · 복도로 돌아가 왼쪽 문으로!');}}}));
   if(enemies.length)e.state.third=true;
  }
  if(stage==='normal_science'){
   back('normal_hall');e.box(0,.8,-7,3,.13,1.5,'#b1a489',true);e.box(-4,.8,-14,2.2,.15,1.3,'#b1a489',true);
   pickup('organHeart','심장 표본',-4,-3);pickup('organLung','폐 표본',4,-4);pickup('organLiver','간 표본',4,-11);
   e.sphere(-4,1.15,-14,.38,'#76a788',e.world,1.2,.5,1.3);for(const x of [-4.24,-3.76])e.sphere(x,1.3,-14.2,.1,'#b5cda1');
   e.interact('frog','개구리 표본을 살펴보기',-4,-12.5,()=>{if(has('frogPiece')){speak('개구리','“고마워. 이제 나도 온전한 모습으로 기억될 수 있어.”');return}if(!['organHeart','organLung','organLiver'].every(has)){e.toast('교실 곳곳의 심장·폐·간 표본을 직접 찾아 주세요.');return}ui.organs(()=>{add('frogPiece');finishFlag('normal_frog','개구리의 표본을 원래 자리로 돌려주었다. 생명의 조각을 받았다.');speak('개구리','“내가 무엇을 잃어버렸는지 기억해 줬구나. 이 조각을 가져가.”');});},2.4);
   e.interact('clean-desk','얼룩진 실험 책상 청소',0,-5.5,()=>{if(F.normal_clean){e.toast('약품 두 개는 가방에서 섞을 수 있다. J · 가방');return}ui.cleaning(()=>{add('chemicalA');add('chemicalB');finishFlag('normal_clean','책상을 깨끗이 닦았다. 과학 선생님에게 약품 A와 B를 받았다.');speak('과학 선생님','“기특하구나. 기억은 제자리를 찾아 줄 때 단단해지지. 약품 A와 B를 같은 양으로 섞어 보렴.”',[['약품을 섞는다',()=>ui.mix(mixComplete)],['가방에 넣는다',close]]);});},2.6);
   npc('해골 모형',4,-16,()=>{if(has('bonePiece')){speak('해골 모형','“반갑군, 동족. 조각을 잘 간직하게.”');return}speak('해골 모형','“자네 얼굴에는 아직 살이 남아 있군. 나를 무얼로 보고 있나?”',[['상아색 점토로 살을 만들어 준다',()=>die('해골은 자신을 바꾸려는 손길에 분노했다. 다른 방법을 찾아야 한다.')],['내 얼굴과 옷을 해골처럼 위장한다',()=>ui.paint(()=>{add('bonePiece');finishFlag('normal_disguise','내 얼굴과 교복을 해골처럼 위장했다. 동족으로 받아들여져 세 번째 조각을 받았다.');close();refresh();e.toast('동족의 조각 획득 · J를 눌러 황금 열쇠 제작');})],['잠시 물러난다',close]],{hair:'#b0b0b0',outfit:'#6b737c'});},{skin:'#d3d2c2',hair:'#d3d2c2',style:'short',outfit:'#777d80'});
   e.interact('craft-station','세 조각으로 황금 열쇠 제작',0,-16.8,craftGolden,2.5);e.marker(0,1.2,-17,'#ebd091');
  }
  if(stage==='hard_entry'){
   back('gate');const cerberus=new e.THREE.Group();e.sphere(0,.9,-9,.9,'#454455',cerberus,1.6,.9,1);for(const x of [-1.1,0,1.1]){e.sphere(x,1.75,-9.55,.53,'#5a4e60',cerberus);for(const dx of [-.17,.17])e.sphere(x+dx,1.84,-10.01,.07,'#ecb2ab',cerberus,1,.55,1,true);}e.world.add(cerberus);e.interact('cerberus','세 머리와 대화하기',0,-7.1,()=>{if(F.hard_gate){go('hard_english');return}speak('케르베로스','세 머리가 서로 다른 질문을 입에 물고 있다.',[['60초 안에 세 질문에 답한다',()=>ui.riddles(()=>{finishFlag('hard_gate','케르베로스의 세 질문에 답했다. 신관의 문이 열렸다.');go('hard_english',['영어 선생님','“두려워도 괜찮아. 네 마음을 네 언어로 말해 보렴.” 교실 앞으로 걸어가 선생님을 만나자.']);})],['장비를 들고 맞선다',()=>{close();if(!has('armor')||!has('shield')){e.toast('갑옷과 방패가 필요하다. 질문으로 통과할 수도 있다.');return}enemy('cerberusBoss','케르베로스',0,-8,{hp:390,speed:6.2,onDeath:()=>{finishFlag('hard_gate','케르베로스를 밀어내고 신관의 문을 열었다.');go('hard_english')}});e.state.third=true;}],['물러난다',close]]);},2.8);
   if(F.hard_gate)door('english-entry','신관 1층으로',0,-19.75,'hard_english');
  }
  if(stage==='hard_english'){
   back('hard_entry');for(const x of [-4,4])for(const z of [-4,-10])e.desk(x,z);
   npc('영어 선생님',0,-14,()=>{if(has('blueEnglish')){speak('영어 선생님','“그 조각을 지키렴. 모든 싸움을 받아 줄 필요는 없단다.”');return}ui.english(()=>{add('blueEnglish');finishFlag('hard_english','두 문장을 완성했다. 두려움 속에서도 계속 나아가겠다는 약속으로 파란 조각을 받았다.');if(!F.hard_studentRolled){F.hard_studentRolled=true;F.hard_studentAppears=Math.random()<.5;}close();refresh();e.toast(F.hard_studentAppears&&!F.hard_studentGone?'학생 그림자가 나타났다. 숨거나 피해 가자.':'파란 조각 획득 · 계단으로 가자.');});},{gender:'boy',hair:'#555463',style:'short',outfit:'#68818f'});
   if(has('blueEnglish')&&F.hard_studentAppears&&!F.hard_studentGone)enemy('englishStudent','길을 막는 학생',3,-9,{hp:180,speed:3.5,passive:true,onHit:()=>{remove('blueEnglish');F.hard_studentGone=true;log('싸움을 받아들이자 파란 조각이 부서졌다. 영어 선생님께 문장을 다시 완성해 돌려받을 수 있다.');enemies.forEach(m=>m.passive=true);e.toast('파란 조각을 잃었다. 영어 선생님에게 다시 도전할 수 있다.');}});
   e.box(-5.3,1.4,-15,1.3,2.8,1,'#43565d',true);e.interact('english-hide','사물함 뒤에 숨기',-4.5,-14,()=>{F.hard_studentGone=true;hiddenFor=8;enemies.forEach(m=>{m.hp=0;m.model.visible=false});checkpoint();e.toast('발소리가 지나갔다. 조각을 지켰다.');},2);
   door('english-stairs','부서진 계단',0,-19.75,'hard_stairs',()=>{if(!has('blueEnglish')){e.toast('영어교실의 파란 조각이 필요하다.');return false}return true});
  }
  if(stage==='hard_math'){
   back('hard_stairs');if(!data.friendName){data.friendName='하루';data.friendGender=e.avatar.gender==='girl'?'boy':'girl';log('복도에서 길을 잃었던 학생 하루가 함께하기로 했다.')}data.weapon='전설의 검';data.attack=90;
   if(!F.dead_mathTeacher)enemy('mathTeacher','수학 선생님의 그림자',0,-11,{hp:340,speed:6.2,onDeath:()=>{finishFlag('hard_math','친구와 힘을 합쳐 수학 선생님의 그림자를 물러나게 했다. 칠판을 살펴보자.');e.toast('그림자를 물리쳤다. 진짜 조각은 직접 찾아야 한다.');}});
   e.sign('모양이 같아도, 같은 것은 아니다.',0,2.5,-19.6,5,'#c9dbcb','#2a4945');e.interact('math-blackboard','칠판의 작은 틈 조사',0,-17.9,()=>{if(!F.dead_mathTeacher){e.toast('선생님의 그림자가 앞을 가로막는다.');return}add('blueMath');finishFlag('hard_mathPiece','칠판의 틈에서 진짜 파란 조각을 찾았다. 학생이 건네던 물건과 달리, 손안에서 차갑게 빛난다.');e.toast('진짜 파란 조각 획득');},2.8);
   npc('감사하다는 학생',4,-14,()=>{if(!F.dead_mathTeacher){e.toast('먼저 선생님의 그림자를 물러나게 해야 한다.');return}speak('학생','“고마워! 이 파란 조각도 가져가!” 이상하게 가볍고, 물건 끝에서 타는 냄새가 난다.',[['받는다',()=>die('그것은 조각처럼 포장된 다이너마이트였다. 진짜 조각은 교실을 직접 조사해서 찾아야 한다.')],['수상해. 받지 않고 칠판을 살핀다',close]]);},{gender:'boy',style:'short',hair:'#91684e'});
   door('math-gym','3층 체육교실',-4,-19.75,'hard_gym',()=>{if(!has('blueMath')){e.toast('칠판의 진짜 조각을 찾아야 한다.');return false}return true});
  }
  if(stage==='hard_gym'){
   back('hard_math');for(const x of [-4,4])e.box(x,.25,-6,2.2,.5,4,'#778694',true);
   npc('체육 선생님',0,-9,()=>{if(!has('greenGym')){ui.survey(()=>{add('greenGym');finishFlag('hard_survey','좋은 기억으로 설문을 채워 초록 조각을 받았다.');chooseShape()});}else chooseShape();},{gender:'boy',style:'short',outfit:'#8b7965'});
   npc('인장을 원하는 학생',4,-14,()=>{if(!has('circle')){e.toast('먼저 체육 선생님의 설문과 도형 문제를 해결하자.');return}if(F.hard_rps){speak('학생','“이번에는 네가 이겼네. 다음 문으로 가도 좋아.”');return}ui.rps(()=>{finishFlag('hard_rps','마지막 구령에 맞춰 바위를 냈다. 원형 인장을 지켜 옥상 문을 열었다.');e.toast('인장을 지켰다. 옥상으로 갈 수 있다.');});},{gender:'boy',style:'short',hair:'#816374'});
   door('gym-roof','옥상으로',0,-19.75,'hard_roof',()=>{if(!F.hard_rps){e.toast('원형 인장을 지켜야 옥상 문이 열린다.');return false}return true});
  }
  if(stage==='hard_maze'){
   back('hard_gym');for(const [x,z,w,d] of [[-2,-2,.35,9],[2,-8,.35,10],[-4,-12,5,.35],[4,-3,5,.35],[0,-16,7,.35]])e.wall(x,z,w,d,3,'#4d576a');e.sign('돌아가는 길도, 길이다.',0,3,-19.7,4);door('maze-exit','체육교실로 돌아가는 문',5,-18.7,'hard_gym');
  }
  if(stage==='hard_roof'){
   e.world.children.filter(o=>o.geometry?.parameters?.height===.15&&o.position.y>4).forEach(o=>o.visible=false);e.scene.background=new e.THREE.Color('#15263b');e.scene.fog.density=.01;back('hard_gym');e.audio.setMode('sad');
   for(const x of [-6.5,6.5]){e.box(x,1,-6,.1,.08,24,'#8597a7');for(let z=5;z>-19;z-=1)e.box(x,.5,z,.045,1,.045,'#637b90');}e.sphere(-10,20,-42,3,'#c4d2df',e.world,1,1,1,true);
   npc('옥상의 학생',F.hard_roof?0:3,F.hard_roof?-5:-13,roofDialogue,{hair:'#524b67',style:'long',outfit:'#6d799a'});
   e.box(0,1.7,-19.5,3.3,3.3,.2,'#7f735e');e.box(0,1.7,-19.35,2.85,2.8,.1,'#132438');e.interact('memory-frame','빈 액자에 조각 끼우기',0,-17.5,()=>{const pieces=['blueEnglish','blueMath','greenGym','blueRoof'];if(!pieces.every(has)){e.toast('말 · 판단 · 용기 · 마음의 네 조각이 필요하다. J에서 가방을 확인하자.');return}ui.frame(pieces.map(id=>[id,ITEM_NAMES[id]]),()=>{finishFlag('hard_frame','네 기억이 한 장의 그림이 되었다. 숨겨진 계단이 나타났다.');go('hard_final');e.toast('60초 안에 계단을 올라 마지막 문에 도착하세요.');});},2.8);
  }
  if(stage.startsWith('hard_')){if(!has('flashlight'))pickup('flashlight','예비 손전등',5,3,()=>true,()=>{e.state.light=true;hud()});if(!has('shield'))pickup('shield','예비 방패',-5,3);if(!has('armor'))pickup('armor','예비 갑옷',-3,3,()=>true,()=>{data.armor=100;hud()});}
  addCompanions();return {x:0,y:0,z:3};
 }
 function buildStoryStairs(){e.resetScene();enemies=[];companions=[];bounds={minX:-2.1,maxX:2.1,minZ:-16.8,maxZ:6.6};const p=stairPlatforms(1.35,3);e.setStairs(p);e.platforms.push(...p);for(const s of p){e.box(0,s.y-.3,s.z,4.8,.6,s.d,'#6e7a87');for(const x of [-2.3,2.3]){e.box(x,s.y+.95,s.z,.05,.07,s.d,'#8aabba');for(let z=s.start+.3;z<s.end;z+=1)e.box(x,s.y+.47,z,.05,.95,.05,'#708b9d');}if(s.index<2){e.box(0,s.y+.015,s.start+.58,4.2,.03,.12,'#a1e5d6');for(const x of [-.25,.25])e.box(x,s.y+.03,s.start+.58,.17,.03,.35,'#d4fff0');e.sign('SPACE / JUMP',0,s.y+1.4,s.start-.12,2.2,'#c1f4e5','#2c5662');}}const last=p.at(-1);bounds.minZ=last.start-.1;for(const x of [-3,3])e.wall(x,-7,.3,30,7,'#42596c');e.wall(0,7,6,.3,7);e.sign('2층 수학교실',0,last.y+2.9,last.start+.05,2.7);e.interact('stairs-math','2층 문 열기',0,last.start+1,()=>{if(e.player.y<last.y-.05)return;finishFlag('hard_stairs','부서진 계단 두 곳을 직접 뛰어넘었다.');go('hard_math',[data.friendName||'복도의 학생','“이 검을 받아. 이번에는 함께 맞서자.” 친구가 전설의 검을 건넸다. Q로 공격하고, 붉은 공격 표시를 피해 움직이자.']);},2);e.audio.setMode('school');addCompanions();return {x:0,y:0,z:5};}
 function buildFinal(){e.resetScene();enemies=[];companions=[];bounds={minX:-1.5,maxX:1.5,minZ:-15.8,maxZ:5.5};e.floorRect(0,3,4,6,0,'#58727e');for(let i=0;i<32;i++)e.floorRect(0,-.25-i*.5,3.8,.5,(i+1)*.14,'#708995');for(const x of [-2.1,2.1])e.wall(x,-5,.3,23,8,'#294456');e.sign('REALITY',0,6.7,-15.8,2.8,'#fff1c7','#677267');e.box(0,5.95,-16,2.2,3,.2,'#becbb5');e.interact('final-door','마지막 문을 두드리기',0,-14.9,()=>{flags().hard_arrived=true;ui.finalDoor(trueEnding);},2);climbTime=60;flags().hard_arrived=false;e.audio.setMode('hope');addCompanions();return {x:0,y:0,z:4};}
 function mixComplete(){add('resinPiece');remove('chemicalA');remove('chemicalB');finishFlag('normal_mix','두 약품을 같은 양으로 섞어 기억의 조각을 만들었다.');e.toast('기억의 조각 획득');}
 function craftGolden(){if(has('goldenKey')){e.toast('황금 열쇠는 이미 가방에 있다.');return}if(!['frogPiece','resinPiece','bonePiece'].every(has)){e.toast('생명 · 기억 · 동족의 세 조각을 모아야 한다. J에서 제작 재료를 확인하세요.');return}add('goldenKey');finishFlag('normal_gold','세 조각을 합쳐 빛나는 황금 열쇠를 만들었다. 과학실 밖으로 따뜻한 바람이 나를 밀어냈다.');go('normal_hall');speak('금빛 기억','세 조각이 서로의 틈을 메우자, 하나의 열쇠가 되었다. 문 너머에서 “콩, 콩” 하는 소리가 들린다.');}
 function kongDialogue(){speak('콩콩 귀신',['“다들 내가 이상하대. 내가 말하면 웃고, 내가 다가가면 피해. 이 소리라도 내면… 누군가는 돌아볼 줄 알았어.”','고개를 숙인 학생의 어깨가 떨린다. 지금 필요한 것은 열쇠도 무기도 아니다.'],[['네 이야기를 듣고 있어. 같이 나가자.',()=>{e.closeModal();nameCompanion('friend');}],['서두르지 않을게. 조금 더 말해 줄래?',()=>{e.closeModal();nameCompanion('friend');}],['시간이 없으니 비켜 줘.',()=>{e.closeModal();e.toast('학생은 더 작게 웅크렸다. 다시 말을 걸어 볼 수 있다.');}]],{kicker:'SOMEONE TO WALK WITH',gender:e.avatar.gender==='girl'?'boy':'girl'});}
 function chooseShape(){speak('체육 선생님','“둥글게 이어지는 길과, 모퉁이를 돌아가는 길. 어떤 것을 고르겠니?”',[['○ 원',()=>{add('circle');finishFlag('hard_circle','원형 인장을 받았다. 그것을 노리는 학생이 가위바위보를 신청했다.');close();e.toast('오른쪽 학생에게 가위바위보를 신청하자.');}],['△ 삼각형',()=>go('hard_maze')]]);}
 function roofDialogue(){if(flags().hard_roof){speak('옥상의 학생','“아직… 내일이 남아 있겠지? 같이 내려갈게.”',[['함께 액자로 가기',close]],{image:ART.roof,alt:'달빛 아래 옥상 학생 일러스트',kicker:'ROOFTOP MEMORY'});return}e.audio.setMode('sad');speak('옥상의 학생',['달빛 아래 난간 곁에 선 학생이 고개를 돌렸다. “아무도 나를 기억하지 못할 거야. 내가 무슨 말을 해도… 아무도 듣지 않았어.”','멀리 불이 켜진 집들이 보인다. 서두르지 않고, 학생에게 닿을 만큼 낮은 목소리로 말한다.'],[['나는 지금 네 이야기를 듣고 있어. 같이 내려가자.',rescueRoof],['말없이 옆에 앉아, 이야기를 기다린다.',rescueRoof],['지금은 바쁘다고 말한다.',()=>{close();e.toast('학생은 여전히 기다리고 있다. 다시 다가가 이야기를 들어 줄 수 있다.');}]],{image:ART.roof,alt:'옥상 난간 곁에 서 있는 학생',kicker:'ROOFTOP MEMORY'});}
 function rescueRoof(){add('blueRoof');finishFlag('hard_roof','옥상 학생의 이야기를 끝까지 들었다. 학생이 난간에서 물러나 함께 내려가기로 했다. 마음의 조각을 받았다.');close();refresh();speak('옥상의 학생','“고마워. 이번에는… 나도 함께 갈게.” 학생이 마지막 파란 조각을 내 손에 올려놓았다.');}
 function chapterClear(route){if(!achievements.clears.includes(route))achievements.clears.push(route);writeJSON('school-achievements-v2',achievements);flags()[route+'_cleared']=true;checkpoint();e.state.running=false;e.audio.setMode('hope');speak(route==='easy'?'EASY CLEAR · 한 사람의 점심':'NORMAL CLEAR · 함께 걷는 밤',route==='easy'?'영양사의 식판이 비워지고, 화장실의 울음이 멎었다. 학교 전체가 조용해진 것은 아니다. 본관 쪽에서 작은 강아지의 울음소리가 들렸다.':`${data.dogName}의 발소리와 ${data.friendName}의 숨소리가 곁에 남았다. 이제 신관의 마지막 목소리를 찾아갈 차례다.`,[['저장하고 로비로',()=>{e.goHome();updateHome();}],['다음 난이도',()=>{e.closeModal();enter(route==='easy'?'normal':'hard');}]],{kicker:'CHAPTER COMPLETE'});updateHome();}
 function hiddenEnding(){achievements.watcher=true;writeJSON('school-achievements-v2',achievements);log('세 번째 창문에서 감시자의 기억을 보았다.');e.state.running=false;ending=true;e.audio.setMode('hidden');speak('HIDDEN ENDING · 감시자',['학교를 망하게 하고 모두를 귀신으로 만든 감시자는 처음부터 나였다. 창문 속 미소가, 내가 외면했던 모든 목소리를 삼켰다.','나는 끝내 학교를 빠져나가지 못했다. 하지만 내 이름을 기억하는 작은 배지는 다음 밤까지 남아 있었다.'],[['홈으로 돌아가기',()=>{e.goHome();updateHome();}]],{image:ART.hidden,alt:'HIDDEN ENDING 감시자 전용 일러스트',kicker:'감시자 배지 획득'});updateHome();}
 function trueEnding(){achievements.truth=true;if(!achievements.clears.includes('hard'))achievements.clears.push('hard');writeJSON('school-achievements-v2',achievements);flags().hard_cleared=true;checkpoint();e.state.running=false;ending=true;e.audio.setMode('hope');speak('TRUE ENDING · 현실로',[`${data.friendName||'친구'}와 함께 문을 밀었다. 빛은 아무것도 지우지 않았다. 그저, 서로를 놓치지 않을 만큼 환하게 비추었다.`,'뒤에서 문이 닫혔다. 귀 기울이지 못했던 목소리들은 이제 내 안에서 이름으로 남았다. 끝이 아닌, 다시 시작되는 우리의 이야기.'],[['홈으로 돌아가기',()=>{e.goHome();updateHome();}]],{image:ART.true,alt:'TRUE ENDING 현실로 전용 일러스트',kicker:'친구와 함께 현실로'});updateHome();}
 function attack(){if(!data.active||e.state.paused||attackCD>0)return;attackCD=.48;$('#swing-effect')?.classList.add('swing');e.sound(data.weapon==='전설의 검'?450:250,.12,.035,'triangle');const p=e.player;const candidates=enemies.filter(m=>m.hp>0&&Math.hypot(m.model.position.x-p.x,m.model.position.z-p.z)<2.7).sort((a,b)=>a.model.position.distanceTo(e.playerModel.position)-b.model.position.distanceTo(e.playerModel.position));const mob=candidates[0];if(!mob){e.toast('가까이 다가온 적에게 Q로 공격하세요.');return}if(mob.opts.onHit&&!mob.hitOnce){mob.hitOnce=true;mob.opts.onHit()}mob.passive=false;if(mob.immortal){mob.stun=.2;return}mob.hp=Math.max(0,mob.hp-data.attack);mob.stun=.3;mob.model.scale.setScalar(1.07);if(!mob.hp)kill(mob);}
 function kill(mob){flags()['dead_'+mob.id]=true;mob.model.visible=false;checkpoint();mob.opts.onDeath?.();}
 function takeDamage(amount){if(hitCD>0||hiddenFor>0||e.state.paused)return;hitCD=1.1;data.hp=Math.max(0,data.hp-amount);data.armor=Math.max(0,data.armor-5);data.mood=data.hp<data.maxHp*.3?'두렵지만 포기하지 않음':'숨을 고르는 중';e.damageFlash();e.sound(95,.16,.05);if(!data.hp)die('그림자가 너무 가까이 다가왔다. 공격 표시를 보고 옆으로 움직이며 다시 맞서 보자.');hud();}
 function die(message){if(e.state.modal==='story-death')return;data.hp=0;data.lives=Math.max(0,data.lives-1);const stage=e.state.stage;if(e.state.route==='hard'){remove('flashlight');remove('shield');remove('armor');data.armor=0;e.state.light=false;}checkpoint();e.showModal('story-death',`<div class="modal-eyebrow">THE NIGHT IS NOT OVER</div><h2 id="modal-title">다시, 눈을 뜰 수 있다면.</h2><p>${h(message)}</p><p class="hint">남은 목숨 ${data.lives} · 단서와 동료의 기억은 저장되었습니다.${e.state.route==='hard'?' 신관의 예비 손전등을 다시 주울 수 있습니다.':''}</p><div class="modal-actions"><button id="story-retry" class="primary">체크포인트에서 재도전</button><button id="story-death-home" class="secondary">홈으로 돌아가기</button></div>`);$('#story-retry').onclick=()=>{data.hp=data.maxHp;if(!data.lives)data.lives=ROUTE_STATS[e.state.route].lives;go(stage);};$('#story-death-home').onclick=e.goHome;}
 function fall(){if(e.state.stage!=='hard_stairs'&&e.state.stage!=='hard_final')return false;data.stairFails++;miniFails++;e.state.falls++;if(e.state.stage==='hard_final'){e.toast('계단 아래에서 다시 시작합니다.');go('hard_final');return true}const tries=4-(miniFails%4);e.showModal('story-fall',`<div class="modal-eyebrow">ONE MORE STEP</div><h2 id="modal-title">발끝이 닿지 않았다.</h2><p>W로 앞으로 이동하며 푸른 발자국 근처에서 SPACE를 눌러 주세요. 모바일도 점프 버튼이 같은 동작을 합니다.</p><p class="hint">이번 도전 ${miniFails%4===0?4:miniFails%4} / 4회 실패 · ${miniFails%4===0?'새로운 네 번의 기회로 다시 시작할 수 있어요.':tries+'번 더 연습할 수 있어요.'}</p><div class="modal-actions"><button id="story-stair-retry" class="primary">계단에서 다시 시작</button><button id="story-stair-home" class="secondary">홈으로</button></div>`);$('#story-stair-retry').onclick=()=>go('hard_stairs');$('#story-stair-home').onclick=e.goHome;return true;}
 function objective(){const F=flags();switch(e.state.stage){case'easy_hall':return !F.easy_cafeSolved?'오른쪽 급식실에서 끝나지 않은 점심의 이유를 찾으세요.':!has('toiletKey')?'왼쪽 화장실의 원혼을 진정시키고 세면대 열쇠를 찾으세요.':'복도 끝 새 문을 세면대 열쇠로 여세요.';case'easy_cafe':return `식판의 기록 ${[0,1,2].filter(i=>F['easy_memory'+i]).length}/3 · 기록을 모아 안쪽 벽의 기억을 조사하세요.`;case'easy_toilet':return !F.easy_toiletAwake?'가운데 변기를 E로 조사하세요.':!F.dead_toilet?'Q로 원혼을 진정시키세요. 붉은 공격 표시를 피해 움직이세요.':'안쪽 세면대의 열쇠를 챙겨 복도로 돌아가세요.';case'normal_hall':return !F.normal_guard?'관리인에게 황동 열쇠를 건네세요.':!has('scienceKey')?'오른쪽 교장실에서 과학실 열쇠를 찾으세요.':!has('goldenKey')?'왼쪽 과학실에서 세 조각을 모아 황금 열쇠를 만드세요.':!data.friendName?'복도 끝 문 앞, 콩콩 소리의 주인에게 말을 걸어 보세요.':'친구와 함께 황금 열쇠로 끝의 문을 여세요.';case'normal_office':return `세 그림자를 진정시키세요. Q 공격 · ${['principal','vice','leader'].filter(id=>F['dead_'+id]).length}/3`;case'normal_science':return `개구리 표본 · 책상 청소와 약품 · 해골 위장 → 세 조각 ${['frogPiece','resinPiece','bonePiece'].filter(has).length}/3. J · 가방/제작`;case'hard_entry':return '케르베로스에게 다가가 E · 60초 안에 세 질문을 푸세요.';case'hard_english':return has('blueEnglish')?'조각을 지키며 계단으로 가세요. 학생과 싸우면 조각을 잃습니다.':'앞쪽 영어 선생님에게 가서 단어 카드로 두 문장을 완성하세요.';case'hard_stairs':return '푸른 발자국에서 W + SPACE. 두 번 착지한 뒤 앞쪽 문으로 가세요.';case'hard_math':return !F.dead_mathTeacher?'친구와 협력해 그림자에 맞서세요. 전설의 검 · Q 공격':'수상한 선물에 주의하고, 칠판을 직접 조사하세요.';case'hard_gym':return !has('greenGym')?'체육 선생님의 설문을 해결하세요. “좋은 기억으로만.”':!has('circle')?'체육 선생님에게 원형 인장을 받으세요.':!F.hard_rps?'오른쪽 학생과 가위바위보. 마지막 구령에 손을 냅니다.':'복도 끝 문으로 옥상에 올라가세요.';case'hard_maze':return '모퉁이를 돌아 안쪽 오른편 출구로 걸어가세요.';case'hard_roof':return !F.hard_roof?'옥상 학생에게 다가가 이야기를 들어 주세요.':'네 조각을 안쪽 빈 액자에 끼우세요.';case'hard_final':return `계단이 사라지기 전에 올라가세요. ${Math.ceil(climbTime)}초 · 문 앞에서 E`;default:return '';}}
 function journal(){const recipe=['frogPiece','resinPiece','bonePiece'];e.showModal('journal',`<div class="modal-eyebrow">INVENTORY & MEMORIES</div><h2 id="modal-title">${h(safeName(e.avatar.name,'나'))}의 기록</h2><p class="hint">${h(objective())}</p><div class="inventory-grid">${data.items.map(i=>`<span>${h(ITEM_NAMES[i])}</span>`).join('')}</div><div class="recipe"><h3>황금 열쇠 제작</h3><p>${recipe.map(i=>`${has(i)?'✓':'○'} ${ITEM_NAMES[i]}`).join(' · ')}</p><div class="modal-actions"><button id="craft-gold" class="primary" ${recipe.every(has)&&!has('goldenKey')?'':'disabled'}>세 조각 합치기</button><button id="mix-chemicals" class="secondary" ${has('chemicalA')&&has('chemicalB')?'':'disabled'}>약품 섞기</button></div></div><h3>이 밤의 기억</h3><ol class="journal-list">${data.journal.map(t=>`<li>${h(t)}</li>`).join('')||'<li>아직 이름을 찾지 못한 목소리들이 있다.</li>'}</ol><div class="modal-actions"><button class="primary" data-close>다시 걷기</button></div>`,true);$('#craft-gold').onclick=craftGolden;$('#mix-chemicals').onclick=()=>ui.mix(mixComplete);}
 function hint(){if(data.dogName)e.toast(`${data.dogName}: ${objective()}`);else e.toast(objective()||'교문을 통과해 원하는 건물로 직접 이동하세요.');}
 function hud(){const el=$('#story-status');if(!el)return;el.hidden=!data.active;if(!data.active){$('#enemy-status').hidden=true;return;}$('#hp-value').textContent=`${Math.ceil(data.hp)} / ${data.maxHp}`;$('#hp-fill').style.width=(data.hp/data.maxHp*100)+'%';$('#story-stats').textContent=`목숨 ${data.lives} · 공격 ${data.attack} · 갑옷 ${data.armor}`;$('#story-weapon').textContent=data.weapon;$('#story-party').textContent=[data.dogName&&'안내견 '+data.dogName,data.friendName&&'친구 '+data.friendName].filter(Boolean).join(' · ')||'혼자 걷는 밤';$('#story-mood').textContent=data.mood;const live=enemies.filter(m=>m.hp>0&&!m.passive);$('#enemy-status').hidden=!live.length;$('#enemy-status').textContent=live.map(m=>`${m.name} ${m.immortal?'???':Math.ceil(m.hp)+'/'+m.maxHp}`).join(' · ');if(own(e.state.stage)){e.setText('#location-title',TITLES[e.state.stage]);e.setText('#objective',objective());e.setText('#stage-label',e.state.route==='hard'?'CHALLENGER · 잃어버린 이름들':e.state.route==='normal'?'NORMAL · 기억을 만드는 법':'EASY · 돌아오지 않은 점심');e.setText('#inventory',`가방 ${data.items.length}개 · J로 기록과 제작`);e.setText('#checkpoint','체크포인트 · '+TITLES[e.state.stage]);$('#jump-guide').hidden=e.state.stage!=='hard_stairs';$('#chase-alert').hidden=true;}}
 function updateHome(){let badge=$('#watcher-badge');if(!badge){badge=document.createElement('span');badge.id='watcher-badge';$('.hero-copy').append(badge)}badge.hidden=!achievements.watcher;badge.textContent='◉ 감시자 배지 보유';$$('[data-route]').forEach(b=>{const r=b.dataset.route;let tag=b.querySelector('.clear-tag');if(!tag){tag=document.createElement('span');tag.className='clear-tag';b.querySelector('.route-info').append(tag)}tag.textContent=achievements.clears.includes(r)?'CLEAR':'';});}
 function audioPanel(){e.showModal('audio-settings',`<div class="modal-eyebrow">SOUND OF THE NIGHT</div><h2 id="modal-title">이 밤의 소리</h2><p>음악과 효과음을 따로 조절할 수 있어요.</p>${[['master','전체'],['bgm','배경 음악'],['sfx','효과음']].map(([key,label])=>`<label class="volume-row">${label}<input type="range" min="0" max="1" step=".05" value="${e.audio.levels[key]}" data-volume="${key}"></label>`).join('')}<div class="modal-actions"><button id="audio-toggle" class="secondary">${e.audio.enabled?'BGM / 소리 끄기':'BGM / 소리 켜기'}</button><button class="primary" data-close>완료</button></div>`);$$('[data-volume]').forEach(input=>input.oninput=()=>{e.audio.levels[input.dataset.volume]=+input.value;e.audio.apply()});$('#audio-toggle').onclick=()=>{e.audio.toggle();audioPanel();e.updateSoundLabels()};}
 function tick(dt,t){ui.tick(dt);e.audio.tick();if(!data.active||!e.state.running||e.state.paused||document.hidden)return;attackCD=Math.max(0,attackCD-dt);hitCD=Math.max(0,hitCD-dt);hiddenFor=Math.max(0,hiddenFor-dt);friendCD=Math.max(0,friendCD-dt);if(attackCD<.2)$('#swing-effect')?.classList.remove('swing');if(e.keys.KeyQ)attack();const p=e.player;const live=enemies.filter(m=>m.hp>0&&!m.passive);if(live.length&&e.state.stage!=='easy_cafe'){e.state.third=true;e.audio.setMode('combat');}else if(!ending&&e.audio.mode==='combat')e.audio.setMode('school');
  for(const mob of enemies){if(mob.hp<=0)continue;mob.label.quaternion.copy(e.camera.quaternion);mob.cooldown=Math.max(0,mob.cooldown-dt);mob.stun=Math.max(0,mob.stun-dt);mob.model.scale.lerp(new e.THREE.Vector3(1,1,1),dt*10);if(mob.passive||hiddenFor>0)continue;const pos=mob.model.position,dx=p.x-pos.x,dz=p.z-pos.z,dist=Math.hypot(dx,dz);mob.model.rotation.y=Math.atan2(-dx,-dz);if(mob.windup>0){mob.windup-=dt;mob.label.material.color.set('#ff9688');if(mob.windup<=0){if(dist<1.9)takeDamage(ROUTE_STATS[e.state.route].damage);mob.cooldown=1.3;mob.label.material.color.set('#ffffff')}continue}if(dist<1.7&&mob.cooldown===0){mob.windup=.65;continue}if(dist>1.3&&!mob.stun){const amount=Math.min(dist-1.1,mob.speed*dt),nx=pos.x+dx/dist*amount,nz=pos.z+dz/dist*amount;if(!blocked(e.colliders,nx,pos.z,0,.3))pos.x=nx;if(!blocked(e.colliders,pos.x,nz,0,.3))pos.z=nz;pos.x=Math.max(bounds.minX,Math.min(bounds.maxX,pos.x));pos.z=Math.max(bounds.minZ,Math.min(bounds.maxZ,pos.z));}}
  if(data.friendName&&friendCD===0&&live.length){const m=live.find(m=>!m.immortal&&Math.hypot(m.model.position.x-p.x,m.model.position.z-p.z)<4);if(m){m.hp=Math.max(0,m.hp-24);friendCD=1.6;e.sound(440,.08,.02);if(!m.hp)kill(m)}}
  for(const c of companions){const pos=c.model.position;const target=new e.THREE.Vector3(Math.max(bounds.minX,Math.min(bounds.maxX,p.x+c.offset)),Math.max(0,p.y),Math.max(bounds.minZ,Math.min(bounds.maxZ,p.z+1.2)));const dx=target.x-pos.x,dz=target.z-pos.z;pos.lerp(target,Math.min(1,dt*3));c.model.rotation.y=Math.atan2(-dx,-dz);if(c.kind==='dog')pos.y+=Math.sin(t*10)*.008;else{c.model.userData.leftLeg.rotation.x=Math.sin(t*10)*.25;c.model.userData.rightLeg.rotation.x=-Math.sin(t*10)*.25;}}
  if(e.state.stage==='hard_final'&&!flags().hard_arrived){climbTime=Math.max(0,climbTime-dt);if(climbTime===0){e.showModal('climb-retry','<h2 id="modal-title">계단이 빛 속으로 흩어졌다.</h2><p>네 조각은 그대로입니다. 계단부터 다시 도전할 수 있어요.</p><div class="modal-actions"><button id="climb-retry" class="primary">계단 다시 나타내기</button><button data-story-home class="secondary">홈으로</button></div>');$('#climb-retry').onclick=()=>go('hard_final');}}
  hud();
 }
 function constrain(){if(!own(e.state.stage))return;const p=e.player;if(!Number.isFinite(p.x)||!Number.isFinite(p.y)||!Number.isFinite(p.z)){e.spawn(0,0,3);return}p.x=Math.max(bounds.minX,Math.min(bounds.maxX,p.x));p.z=Math.max(bounds.minZ,Math.min(bounds.maxZ,p.z));}
 function handleWin(){if(data.active&&flags().normal_chase){chapterClear('normal');return true}return false;}
 function setup(){const status=document.createElement('div');status.id='story-status';status.hidden=true;status.innerHTML='<div class="hp-line"><span>HP</span><b id="hp-value"></b></div><div class="hp-track"><i id="hp-fill"></i></div><small id="story-stats"></small><span id="story-weapon"></span><small id="story-party"></small><small id="story-mood"></small>';$('#hud').append(status);const en=document.createElement('div');en.id='enemy-status';en.hidden=true;$('#hud').append(en);const swing=document.createElement('div');swing.id='swing-effect';$('#hud').append(swing);const bar=document.createElement('div');bar.className='story-tools';bar.innerHTML='<button id="journal-button">가방·기록 <kbd>J</kbd></button><button id="hint-button">힌트 <kbd>H</kbd></button><button id="sound-settings">♫ 소리</button><button id="story-home">⌂ 홈</button>';$('#hud').append(bar);$('#journal-button').onclick=journal;$('#hint-button').onclick=hint;$('#sound-settings').onclick=audioPanel;$('#story-home').onclick=e.goHome;document.addEventListener('click',ev=>{if(ev.target.closest('[data-story-home]'))e.goHome()});updateHome();}
 function legacyStage(stage){enemies=[];companions=[];bounds=stage==='chase'?{minX:-2.65,maxX:2.65,minZ:-65,maxZ:7}:{minX:-24,maxX:24,minZ:-24,maxZ:28};if(stage==='chase')addCompanions();}
 setup();
 return {ui,legacyStage,enter,intro,startFresh,owns:own,build,tick,attack,journal,hint,hud,constrain,fall,handleWin,audioPanel,updateHome,save:()=>data,restore:(raw,stage,route)=>{data=normalizeStory(raw);if(own(stage)){data.active=true;if(!raw?.maxHp){data.maxHp=ROUTE_STATS[route].hp;data.hp=data.maxHp;}if(data.hp===0)data.hp=data.maxHp;if(!data.lives)data.lives=ROUTE_STATS[route].lives;}ending=false;},get hasFlashlight(){return has('flashlight')},get active(){return data.active},get isStairs(){return e.state.stage==='hard_stairs'},get forceThird(){return data.active&&enemies.some(m=>m.hp>0&&!m.passive&&!m.immortal)},cancelModal:()=>ui.cancel(),onHome:()=>{ui.cancel();enemies=[];companions=[];ending=false;e.audio.setMode('menu');updateHome()},appearance:a=>flags().normal_disguise&&e.state.stage==='normal_science'?{...a,skin:'#ddd8c9',outfit:'#353c45'}:a,snapshot:()=>({data:structuredClone(data),achievements:structuredClone(achievements),bounds:{...bounds},enemies:enemies.map(m=>({id:m.id,name:m.name,hp:m.hp,passive:m.passive,x:m.model.position.x,z:m.model.position.z})),companions:companions.map(c=>({kind:c.kind,name:c.name,visible:c.model.visible})),mini:ui.snapshot(),climbTime})};
}
