import * as THREE from './vendor/three.module.js';
import {DIFFICULTIES,groundAt,movePlayer,jump,stairPlatforms} from './physics.js?v=2';
import {DEFAULT_AVATAR,avatarSVG,normalizeAvatar} from './avatar.js?v=2';

import {createCampaign} from './campaign.js?v=2';
import {AudioManager} from './audio.js?v=2';
import {safeName,escapeHTML} from './story-state.js?v=2';
const audio=new AudioManager();let campaign;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],canvas=$('#world');
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const write=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value))}catch{}};
let avatar=normalizeAvatar(read('school-avatar-v1',{}));
const state={stage:'home',route:'normal',gate:false,notes:[],key:false,third:false,light:true,running:false,paused:false,modal:null,elapsed:0,falls:0,caught:0,jumps:0,checkpoint:'gate',comfort:read('school-comfort',false),sound:audio.enabled};
let renderer,scene,camera,world,playerModel,ghost,flash,flashTarget,platforms=[],colliders=[],interactables=[],stairData=[],decorations=[],keys={},closest=null,toastTimer,frameTime=0,stepClock=0,jumpCounted=-1,ghostTrail=[],dragging=false,lastX=0,lastY=0,lookPitch=0,saveClock=0;
const player={x:0,y:0,z:16,yaw:0,vy:0,grounded:true};
const controls={forward:0,side:0,sprint:false};
function sound(freq=440,duration=.12,volume=.04,type='sine'){audio.sfx(freq,duration,volume,type)}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
function timeLabel(t){return `${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`;}
const matCache=new Map();
function material(color,emissive=false){const key=color+emissive;if(!matCache.has(key))matCache.set(key,emissive?new THREE.MeshBasicMaterial({color}):new THREE.MeshStandardMaterial({color,roughness:.9,metalness:.05}));return matCache.get(key)}
function box(x,y,z,w,h,d,color,solid=false,parent=world){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material(color));mesh.position.set(x,y,z);parent.add(mesh);if(solid)colliders.push({x,y,z,w,h,d});return mesh;}
function sphere(x,y,z,r,color,parent=world,sx=1,sy=1,sz=1,basic=false){const m=new THREE.Mesh(new THREE.SphereGeometry(r,20,14),material(color,basic));m.position.set(x,y,z);m.scale.set(sx,sy,sz);parent.add(m);return m;}
function cylinder(x,y,z,top,bottom,height,color,parent=world){const m=new THREE.Mesh(new THREE.CylinderGeometry(top,bottom,height,12),material(color));m.position.set(x,y,z);parent.add(m);return m;}
function floorRect(x,z,w,d,y=0,color='#384754'){box(x,y-.18,z,w,.36,d,color);platforms.push({x,z,w,d,y});}
function wall(x,z,w,d,h=4.4,color='#3f4c5b'){return box(x,h/2,z,w,h,d,color,true)}
function sign(text,x,y,z,w=2,color='#e0d3bd',background='#223845',rotation=0){const c=document.createElement('canvas');c.width=768;c.height=192;const c2=c.getContext('2d');c2.fillStyle=background;c2.fillRect(0,0,768,192);c2.strokeStyle=color;c2.lineWidth=3;c2.strokeRect(9,9,750,174);c2.fillStyle=color;c2.font='700 56px "Noto Sans KR Variable",sans-serif';c2.textAlign='center';c2.textBaseline='middle';c2.fillText(text,384,100,716);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const m=new THREE.Mesh(new THREE.PlaneGeometry(w,w/4),new THREE.MeshBasicMaterial({map:tex,side:THREE.DoubleSide}));m.position.set(x,y,z);m.rotation.y=rotation;world.add(m);return m;}
function lamp(x,y,z,color='#d1cbac'){box(x,y,z,.75,.07,.3,color);const glow=new THREE.Mesh(new THREE.PlaneGeometry(1.4,.6),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.09,depthWrite:false,side:THREE.DoubleSide}));glow.position.set(x,y-.03,z);glow.rotation.x=-Math.PI/2;world.add(glow);}
function marker(x,y,z,color='#a4dcca'){const m=new THREE.Mesh(new THREE.OctahedronGeometry(.15),new THREE.MeshBasicMaterial({color}));m.position.set(x,y,z);world.add(m);decorations.push({m,base:y});return m;}
function interact(id,label,x,z,action,range=2.3){interactables.push({id,label,x,z,action,range});}
function textureFloor(){const c=document.createElement('canvas');c.width=c.height=128;const q=c.getContext('2d');q.fillStyle='#89949c';q.fillRect(0,0,128,128);q.strokeStyle='#60717a';q.lineWidth=2;q.strokeRect(0,0,128,128);q.strokeStyle='#7c898f';q.beginPath();q.moveTo(64,0);q.lineTo(64,128);q.moveTo(0,64);q.lineTo(128,64);q.stroke();const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(10,18);t.colorSpace=THREE.SRGBColorSpace;return t;}
function resetScene(outside=false){if(scene){const shared=new Set(matCache.values());scene.traverse(o=>{o.geometry?.dispose();for(const m of (Array.isArray(o.material)?o.material:[o.material]))if(m&&!shared.has(m)){m.map?.dispose();m.dispose();}})}scene=new THREE.Scene();scene.background=new THREE.Color(outside?'#101727':'#0b131d');scene.fog=new THREE.FogExp2(outside?'#182238':'#101b2b',outside?.018:.025);world=new THREE.Group();scene.add(world);platforms=[];colliders=[];interactables=[];decorations=[];const hemi=new THREE.HemisphereLight('#b1c8e9','#374552',outside?1.65:1.85);scene.add(hemi);const moonLight=new THREE.DirectionalLight('#a0b9eb',2.2);moonLight.position.set(-12,20,12);scene.add(moonLight);const warm=new THREE.DirectionalLight('#e8b697',.35);warm.position.set(8,4,-8);scene.add(warm);flash=new THREE.SpotLight('#f2e5bd',state.light?30:0,24,Math.PI/4,.7,1.2);flashTarget=new THREE.Object3D();flash.target=flashTarget;scene.add(flash,flashTarget);playerModel=createCharacter(campaign?.appearance(avatar)||avatar);scene.add(playerModel);playerModel.visible=false;}
function createCharacter(a){const g=new THREE.Group();const skin=a.skin,hair=a.hair;
 const torso=box(0,1.06,0,.48,.57,.24,a.outfit,false,g);torso.rotation.z=.015;
 box(-.29,1.04,0,.15,.52,.18,a.outfit,false,g);box(.29,1.04,0,.15,.52,.18,a.outfit,false,g);sphere(-.29,.73,0,.085,skin,g,1,1.1,1);sphere(.29,.73,0,.085,skin,g,1,1.1,1);
 if(a.gender==='girl')cylinder(0,.71,0,.26,.37,.27,'#303c60',g);else box(0,.71,0,.48,.25,.26,'#303c60',false,g);
 const leftLeg=new THREE.Group(),rightLeg=new THREE.Group();leftLeg.position.set(-.14,.58,0);rightLeg.position.set(.14,.58,0);g.add(leftLeg,rightLeg);for(const leg of [leftLeg,rightLeg]){box(0,-.2,0,.14,.42,.15,a.gender==='girl'?skin:'#303c60',false,leg);box(0,-.34,0,.145,.2,.155,'#d8dfec',false,leg);box(0,-.51,-.025,.17,.14,.28,'#252b40',false,leg);}
 box(0,1.34,-.03,.18,.12,.17,skin,false,g);sphere(0,1.62,0,.36,skin,g,a.faceShape==='round'?1.04:a.faceShape==='tapered'?.96:1,1.02,.84);
 // A continuous crown sits over the entire scalp; layered fringe overlaps it.
 const cap=new THREE.Mesh(new THREE.SphereGeometry(.376,24,16,0,Math.PI*2,0,Math.PI*.59),material(hair));cap.scale.set(1,1.13,.89);cap.position.set(0,1.66,.008);g.add(cap);
 sphere(0,1.65,.12,.32,hair,g,1,1.04,.77);
 for(let i=0;i<7;i++){const lock=new THREE.Mesh(new THREE.ConeGeometry(.105,.33+(i%2)*.045,5),material(hair));lock.position.set((i-3)*.081,1.75-(Math.abs(i-3)*.014),-.253+Math.abs(i-3)*.018);lock.rotation.z=Math.PI+(i-3)*.09;g.add(lock);}
 for(const side of [-1,1]){sphere(side*.31,1.55,.01,.15,hair,g,.64,a.style==='short'?1.15:2.05,.9);if(['long','side','curly'].includes(a.style))sphere(side*.26,1.16,.16,.17,hair,g,.8,2.4,.65);}
 if(a.style==='bob')sphere(0,1.38,.16,.32,hair,g,1,1.04,.55);
 if(a.style==='ponytail'){sphere(0,1.7,.39,.18,hair,g,.8,1.8,1.1);sphere(0,1.26,.38,.15,hair,g,.65,2.1,.8);}
 if(a.style==='twintail')for(const side of [-1,1]){sphere(side*.43,1.51,.11,.16,hair,g,.9,2.3,.8);sphere(side*.44,1.72,.04,.06,'#b4aac9',g);}
 if(a.style==='braid')for(let i=0;i<7;i++)sphere(.32+(i%2)*.04,1.4-i*.085,.17,.084,hair,g,1,.85,1);
 if(a.style==='curly')for(const side of [-1,1])for(let i=0;i<5;i++)sphere(side*(.31+(i%2)*.04),1.43-i*.11,.12,.12,hair,g,.8,1,.7);
 if(a.style==='side'){const sweep=sphere(.11,1.79,-.28,.21,hair,g,.8,1.1,.35);sweep.rotation.z=.45;}
 if(a.outfitType==='hoodie'){sphere(0,1.28,.11,.25,'#9aa5ba',g,1,.5,.9);box(0,.96,-.14,.28,.15,.025,'#33445c',false,g);}
 if(a.outfitType==='sport'){for(const side of [-1,1])box(side*.3,1.06,-.098,.05,.45,.015,'#d9e3e7',false,g);box(0,1.05,-.132,.03,.48,.018,'#e3e3df',false,g);}
 if(a.outfitType==='cardigan')box(0,1.13,-.136,.19,.37,.019,'#dbd8d3',false,g);
 if(a.outfitType==='sailor')box(0,1.31,.02,.57,.065,.35,'#b4c7da',false,g);
 const face=document.createElement('canvas');face.width=256;face.height=192;const q=face.getContext('2d');q.clearRect(0,0,256,192);
 for(const cx of [70,186]){q.fillStyle='#fbf9ff';q.beginPath();q.ellipse(cx,87,35,a.eyeShape==='sharp'?25:33,0,0,Math.PI*2);q.fill();const grad=q.createLinearGradient(0,60,0,118);grad.addColorStop(0,'#221d3a');grad.addColorStop(.55,a.eyes);grad.addColorStop(1,'#d1d2ef');q.fillStyle=grad;q.beginPath();q.ellipse(cx,91,19,28,0,0,Math.PI*2);q.fill();q.fillStyle='#252039';q.beginPath();q.ellipse(cx,89,9,23,0,0,Math.PI*2);q.fill();q.fillStyle='white';q.beginPath();q.arc(cx-8,77,8,0,7);q.fill();q.beginPath();q.arc(cx+7,104,3,0,7);q.fill();q.strokeStyle='#332b3e';q.lineWidth=8;q.beginPath();q.ellipse(cx,87,35,29,0,Math.PI,Math.PI*2);q.stroke();q.strokeStyle=hair;q.lineWidth=5;q.beginPath();q.moveTo(cx-25,44);q.quadraticCurveTo(cx,34,cx+25,44);q.stroke();q.fillStyle='#d9839344';q.beginPath();q.ellipse(cx,133,22,8,0,0,7);q.fill();}
 q.strokeStyle='#b78980';q.lineWidth=3;q.beginPath();q.moveTo(128,112);q.lineTo(a.nose==='soft'?122:128,127);q.stroke();q.strokeStyle='#a26d78';q.lineWidth=4;q.beginPath();q.moveTo(112,154);q.quadraticCurveTo(128,a.mouth==='smile'?166:151,144,154);q.stroke();
 const ft=new THREE.CanvasTexture(face);ft.colorSpace=THREE.SRGBColorSpace;const f=new THREE.Mesh(new THREE.PlaneGeometry(.57,.43),new THREE.MeshBasicMaterial({map:ft,transparent:true,depthWrite:false}));f.rotation.y=Math.PI;f.position.set(0,1.56,-.301);g.add(f);
 const collar1=box(-.09,1.29,-.145,.19,.13,.015,'#dce0f0',false,g);collar1.rotation.z=-.35;const collar2=box(.09,1.29,-.145,.19,.13,.015,'#dce0f0',false,g);collar2.rotation.z=.35;box(0,1.18,-.158,.11,.13,.02,'#b7788c',false,g);g.userData={leftLeg,rightLeg};return g;}
function schoolBuilding(x,z,w,name,route){const depth=8,height=route==='hard'?11:8.5;box(x,height/2,z,w,height,depth,route==='hard'?'#424457':'#4c5369',true);box(x,height+.15,z,w+.7,.35,depth+.8,'#283143');box(x,1.3,z+depth/2+.02,w,1.7,.08,'#3d4757');for(let floor=0;floor<3;floor++){const yy=2.6+floor*2.6;box(x,yy+1.05,z+depth/2+.07,w+.2,.15,.15,'#282f41');for(let xx=x-w/2+1;xx<x+w/2-.5;xx+=1.8){const warm=(Math.floor(xx*3+floor*4)%5===0);box(xx,yy,z+depth/2+.1,1.03,1.35,.07,warm?'#b39270':'#33485f');box(xx,yy,z+depth/2+.15,.055,1.35,.04,'#222d40');box(xx,yy,z+depth/2+.15,1.03,.05,.04,'#222d40');}}
 box(x,1.45,z+depth/2+.2,1.6,2.9,.22,'#192c38');box(x-.44,1.4,z+depth/2+.34,.61,2.15,.04,'#5b6c75');box(x+.44,1.4,z+depth/2+.34,.61,2.15,.04,'#536673');box(x,3,z+depth/2+.8,3.2,.22,1.6,'#272f45');sign(name+' · '+DIFFICULTIES[route].label,x,3.67,z+depth/2+.2,3.1,route==='normal'?'#f2c89d':'#b9d2d0');marker(x,2.3,z+depth/2+1,route==='normal'?'#ffb185':'#90cfc9');interact(route,name+' 입장 · '+DIFFICULTIES[route].label,x,z+depth/2+1,()=>{if(!state.gate){toast('먼저 교문의 잠금을 해제하세요.');return}campaign.enter(route);},2.8);}
function buildCourtyard(){resetScene(true);floorRect(0,4,54,58,0,'#394452');const plane=new THREE.Mesh(new THREE.PlaneGeometry(54,58),new THREE.MeshStandardMaterial({map:textureFloor(),color:'#5c677d',roughness:1}));plane.rotation.x=-Math.PI/2;plane.position.set(0,.009,4);world.add(plane);wall(-25,4,.8,58,2.3,'#333f51');wall(25,4,.8,58,2.3,'#333f51');wall(0,29,50,.8,2.3,'#333f51');wall(0,-25,50,.8,2.3,'#333f51');schoolBuilding(0,-12,18,'본관','normal');schoolBuilding(-16,-7,10,'급식실','easy');schoolBuilding(16,-7,10,'신관','hard');
 for(const x of [-6,6]){box(x,1.8,11,1.1,3.6,1.1,'#657080',true);sphere(x,3.75,11,.27,'#eed1a2',world,1,1,1,true);sign('정문',x,2.3,11.57,.9,'#e1d3bb','#3d4a59');}for(const side of [-1,1]){box(side*15.3,1.4,11,17.5,.14,.15,'#344352',true);box(side*15.3,.6,11,17.5,.14,.15,'#344352');for(let x=6.6;x<24;x+=.6)box(side*x,1.45,11,.055,2.65,.055,'#6a7586');colliders.push({x:side*15.3,y:1.35,z:11,w:17.5,h:2.7,d:.1});}
 if(!state.gate){const gates=new THREE.Group();for(let x=-5.4;x<=5.4;x+=.48)box(x,1.5,11,.07,3,.09,'#7d8797',false,gates);for(const yy of [.6,1.9,2.85])box(0,yy,11,11,.09,.12,'#8894a5',false,gates);world.add(gates);gates.name='gate';colliders.push({x:0,y:1.5,z:11,w:11,h:3,d:.1,id:'gate'});box(0,1.45,11.14,.48,.7,.12,'#1f293b');sign('••••',0,1.53,11.23,.37,'#9fdbcd','#152831');interact('gate','교문 잠금장치 조사',0,12,()=>openKeypad('gate'),3.3);sign('네 번의 종소리 · 4 4 4 4',0,3.55,11.12,3.9,'#c8cfcc','#273745');}
 for(const x of [-10,10])for(const z of [5,18]){cylinder(x,2.5,z,.08,.11,5,'#536478');sphere(x,5.1,z,.3,'#f4d5a2',world,1,1.2,1,true);const pool=new THREE.Mesh(new THREE.CircleGeometry(2.4,24),new THREE.MeshBasicMaterial({color:'#e6ca98',transparent:true,opacity:.06,depthWrite:false}));pool.rotation.x=-Math.PI/2;pool.position.set(x,.027,z);world.add(pool);}
 for(const x of [-22,22])for(const z of [-1,7,20]){cylinder(x,1.25,z,.18,.28,2.5,'#39444c');for(let h=0;h<3;h++){const tree=new THREE.Mesh(new THREE.ConeGeometry(1.4-h*.23,2.5,7),material('#283f45'));tree.position.set(x,2.6+h*1.2,z);world.add(tree);}}
 sphere(-23,28,-60,4,'#b8c4d6',world,1,1,1,true);const stars=[];for(let i=0;i<180;i++){const n=Math.sin(i*79.17)*43758.5;const v=n-Math.floor(n);stars.push(Math.sin(i*2.4)*100,18+v*50,-25-Math.cos(i)*70)}const sg=new THREE.BufferGeometry();sg.setAttribute('position',new THREE.Float32BufferAttribute(stars,3));world.add(new THREE.Points(sg,new THREE.PointsMaterial({color:'#becce0',size:.095,transparent:true,opacity:.7})));}
function chalkboard(){const c=document.createElement('canvas');c.width=1536;c.height=768;const q=c.getContext('2d');q.fillStyle='#284747';q.fillRect(0,0,1536,768);q.strokeStyle='#86a797';q.lineWidth=5;q.strokeRect(18,18,1500,732);q.textAlign='center';q.fillStyle='#e3e1c9';q.font='700 132px "Noto Sans KR Variable"';q.fillText('종 → 달 → 별',768,260);q.fillStyle='#bdceba';q.font='500 69px "Noto Sans KR Variable"';q.fillText('세 기호의 숫자를 순서대로',768,440);q.fillStyle='#96b3a0';q.font='400 55px "Noto Sans KR Variable"';q.fillText('아직, 집에 갈 수 있어.',768,610);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const m=new THREE.Mesh(new THREE.PlaneGeometry(5.5,2.55),new THREE.MeshBasicMaterial({map:t}));m.position.set(-7,2.15,-11.7);world.add(m);}
function corridorShell(length=28){floorRect(0,(-length+6)/2,6,length+6,0,'#5b6571');wall(-3,(-length+6)/2,.28,length+6,4.6);wall(3,(-length+6)/2,.28,length+6,4.6);wall(0,6,6,.3,4.6);wall(0,-length,6,.3,4.6);box(0,4.6,(-length+6)/2,6,.2,length+6,'#434b57');for(const x of [-2.83,2.83])box(x,1.1,(-length+6)/2,.07,1.6,length+6,'#344c58');for(let z=2;z>-length;z-=6){lamp(0,4.46,z);for(const x of [-2.81,2.81]){const win=box(x,2.6,z,.035,1.4,2.6,'#51667c');box(x,2.6,z,.04,.045,2.6,'#213748');box(x,2.6,z,.04,1.4,.05,'#213748');}}}
function desk(x,z){box(x,.84,z,1.1,.12,.7,'#b0a18a',true);for(const dx of [-.44,.44])for(const dz of [-.26,.26])box(x+dx,.41,z+dz,.035,.82,.035,'#516375');box(x,.46,z+.7,.55,.09,.55,'#8a8175',true);box(x,.75,z+.95,.58,.65,.06,'#8e837b',true);}
function buildInterior(){resetScene();const route=DIFFICULTIES[state.route];floorRect(0,-8,6,29,0,'#656d75');floorRect(-7,-7,8,10,0,'#6c7178');wall(3,-8,.3,29);wall(-3,1.5,.3,7);wall(-3,-14,.3,15);wall(-11,-7,.3,10);wall(-7,-12,8,.3);wall(-7,-2,8,.3);wall(0,6.5,6,.3);wall(0,-22.5,6,.3);box(-4,4.4,-8,14,.2,29,'#404955');for(let z=2;z>=-20;z-=5){lamp(0,4.2,z);box(2.8,2.5,z,.06,1.45,2.1,'#526b83');box(2.76,2.5,z,.05,1.45,.06,'#263947');box(2.76,2.5,z,.05,.06,2.1,'#263947');}
 for(const z of [-4.7,-8.9])for(const x of [-8.8,-5.9])desk(x,z);box(-7,2.15,-11.79,5.6,2.65,.1,'#244648');chalkboard();sign(state.route==='easy'?'조리 실습실':'6학년 4반',-3.05,3.45,-5,2,'#e1d3b7','#3b4e59',Math.PI/2);sign('← 단서가 남은 교실',0,3.55,-2,3.8,'#ced3bb','#344657');
 const pts=[[-8.8,-4.7],[-8.8,-8.9],[-5.9,-8.9]],symbols=['종','달','별'],colors=['#edb3a0','#bfc5ee','#ded098'];pts.forEach(([x,z],i)=>{if(!state.notes.includes(i)){const paper=box(x,.92,z,.42,.018,.36,colors[i]);paper.rotation.y=.15-i*.15;const mark=marker(x,1.45,z,colors[i]);mark.name='note-'+i;interact('note-'+i,symbols[i]+' 그림이 있는 쪽지',x,z,()=>openNote(i,symbols[i],route.code[i]),2.05);}});
 box(1.3,1.25,-17.9,1.55,2.5,.65,'#3d5960',true);sign(state.key?'열쇠 획득 완료':'비상 열쇠 보관함',1.3,2.22,-17.53,1.45,'#badad4','#2d4850');box(1.3,1.15,-17.5,.8,.7,.02,'#243944');marker(1.3,2.8,-17.3,'#9bdccb');interact('cabinet',state.key?'빈 열쇠 보관함':'비상 열쇠 보관함 열기',1.3,-16.8,()=>{if(state.key){toast('이미 비상 열쇠를 챙겼습니다. 복도 끝 비상문으로 가세요.');return}if(state.notes.length<3){toast('교실에서 종·달·별 쪽지 3장을 먼저 찾아야 합니다. ('+state.notes.length+'/3)');return}openKeypad('cabinet')},2.2);
 box(0,1.5,-22.24,1.8,3,.13,'#315356');sign('비상 계단 ↑',0,3.5,-22.14,2.5,'#b2edd0','#234740');interact('stair-door','비상 계단으로 이동',0,-21.2,()=>{if(!state.key){toast('비상문이 잠겨 있습니다. 열쇠 보관함을 열어 보세요.');return}loadStage('stairs');toast('세 곳의 끊어진 계단을 건너세요. 푸른 발자국 위에서 점프!')},2.3);
 lamp(-7,4.2,-6);}
function buildStairs(){resetScene();stairData=stairPlatforms(DIFFICULTIES[state.route].gap);platforms.push(...stairData);for(const p of stairData){box(0,p.y-.32,p.z,4.8,.64,p.d,'#64717d');for(const x of [-2.3,2.3]){box(x,p.y+.9,p.z,.055,.07,p.d,'#6a8697');for(let z=p.start+.3;z<p.end;z+=1)box(x,p.y+.45,z,.05,.9,.05,'#657c8e');}if(p.index<3){box(0,p.y+.012,p.start+.47,4.2,.018,.085,'#a1e5d6');for(const x of [-.3,.3]){box(x,p.y+.018,p.start+.48,.15,.021,.35,'#a4e6d8');box(x,p.y+.019,p.start+.7,.17,.025,.09,'#a4e6d8');}sign('↓  SPACE  ↓',0,p.y+1.28,p.start-.13,2,'#b7e6e0','#2f4f5d');}
 // Exposed stair treads along the wall make the collapsed flights legible.
 for(let j=0;j<5;j++)box(-2.8,p.y-.55+j*.11,p.end-.3-j*.43,.48,.16,.4,'#506577');}
 const end=stairData.at(-1).start;wall(-3.25,(end+8)/2,.4,8-end,8,'#354b61');wall(3.25,(end+8)/2,.4,8-end,8,'#354b61');wall(0,7.5,6.5,.3,8);wall(0,end-.8,6.5,.3,8);floorRect(0,-10,6,65,-7,'#111d2b');for(let z=3;z>end;z-=7){lamp(0,6,z);sign('계단실',3.02,3.7,z,1.8,'#95bbca','#334a62',-Math.PI/2);}const top=stairData.at(-1);box(0,top.y+1.5,end+.08,1.9,3,.1,'#42646b');sign('옥상 연결 복도 →',0,top.y+3.15,end+.16,2.7,'#b6e9dc','#2d4b55');marker(0,top.y+2.1,end+1.2);interact('chase-door','옥상 연결 복도로',0,end+1.2,()=>{if(player.y<top.y-.1){return}loadStage('chase');toast('문이 닫혔습니다. Shift를 눌러 달리세요!')},2);}
function createGhost(){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.ConeGeometry(.55,2.2,14),new THREE.MeshStandardMaterial({color:'#272d42',transparent:true,opacity:.9,roughness:1}));body.position.y=1;g.add(body);sphere(0,2.1,0,.38,'#bac3c6',g,.9,1.25,.8);sphere(0,2.25,.1,.43,'#222237',g,1,1.18,.75);for(const x of [-.12,.12])sphere(x,2.15,-.31,.046,'#edb5bb',g,1,.45,1,true);box(-.56,1.4,0,.13,1.1,.12,'#34354a',false,g);box(.56,1.4,0,.13,1.1,.12,'#34354a',false,g);return g;}
function buildChase(){resetScene();corridorShell(66);for(const [x,z] of [[-1.6,-9],[1.6,-20],[-1.6,-32],[1.6,-44]]){box(x,.55,z,2.6,1.1,1.05,'#79746f',true);box(x,.12,z,2.8,.2,1.25,'#4e5a64');sign(x<0?'오른쪽으로 →':'← 왼쪽으로',0,2.4,z+1,2.6,'#b9e6d5','#2a4950');}
 for(let z=-4;z>-63;z-=5){box(0,.02,z,.09,.035,.8,'#94cfc0');box(2.8,.3,z,.08,.1,.35,'#a2dbb6');}box(0,1.6,-65.78,2,3.2,.1,'#3a735d');sign('EXIT  비상구',0,3.8,-65.62,2.7,'#c4ffe0','#245f44');sign('끝까지 달려!',0,2.3,-65.6,1.8,'#c4ffe0','#245f44');ghost=createGhost();ghost.position.set(0,0,13);scene.add(ghost);ghostTrail=[{x:0,z:5}];interact('exit','문을 열고 탈출',0,-64.5,win,2.4);}
function spawn(x,y,z,yaw=0){Object.assign(player,{x,y,z,yaw,vy:0,grounded:true});lookPitch=0;keys={};jumpCounted=-1;}
function loadStage(stage,options={}){
 campaign?.cancelModal();state.stage=stage;state.paused=false;state.running=true;state.modal=null;$('#modal-backdrop').hidden=true;$('#home').hidden=true;$('#hud').hidden=false;document.body.classList.add('playing');closest=null;state.checkpoint=stage;keys={};player.vy=0;
 if(campaign?.owns(stage)){const start=campaign.build(stage);spawn(start.x,start.y,start.z,start.yaw||0);}
 else {if(stage==='gate'){buildCourtyard();spawn(0,0,state.gate?9:16)}else if(stage==='interior'){buildInterior();spawn(0,0,3)}else if(stage==='stairs'){buildStairs();spawn(0,0,5)}else if(stage==='chase'){buildChase();spawn(0,0,5)}campaign?.legacyStage(stage);}
 if(options.retry)toast('체크포인트에서 다시 시작합니다.');updateHUD();saveProgress();
}
function saveProgress(){if(state.running&&state.stage!=='home'&&state.stage!=='win')write('school-save-v2',{version:2,stage:state.stage,route:state.route,gate:state.gate,notes:state.notes,key:state.key,elapsed:state.elapsed,falls:state.falls,caught:state.caught,jumps:state.jumps,story:campaign?.save()});}
function startNew(){audio.unlock();campaign.startFresh();state.gate=false;state.notes=[];state.key=false;state.elapsed=0;state.falls=0;state.caught=0;state.jumps=0;state.third=false;state.light=true;loadStage('gate');campaign.intro();sound(400,.2)}
function continueGame(){audio.unlock();const saved=read('school-save-v2',null)||read('school-save-v1',null);if(saved&&[1,2].includes(saved.version)&&(['gate','interior','stairs','chase'].includes(saved.stage)||campaign.owns(saved.stage))&&DIFFICULTIES[saved.route]){campaign.restore(saved.story,saved.stage,saved.route);state.route=saved.route;state.light=!campaign.active||campaign.hasFlashlight;state.gate=saved.gate===true;state.key=saved.key===true;state.notes=Array.isArray(saved.notes)?saved.notes.filter(i=>[0,1,2].includes(i)):[];for(const k of ['elapsed','falls','caught','jumps'])state[k]=Number.isFinite(saved[k])?Math.max(0,saved[k]):0;loadStage(saved.stage);toast('저장한 체크포인트에서 이어갑니다.');}else startNew();}
function goHome(){saveProgress();state.running=false;state.paused=false;state.stage='home';state.modal=null;keys={};campaign?.onHome();document.exitPointerLock?.();$('#modal-backdrop').hidden=true;$('#hud').hidden=true;$('#home').hidden=false;document.body.classList.remove('playing');buildCourtyard();updateStartButton();}
function updateStartButton(){const saved=read('school-save-v2',null)||read('school-save-v1',null);$('#start').innerHTML='새 게임 <span>↗</span>';$('#continue-game').hidden=!saved;campaign?.updateHome();}
function updateHUD(){const d=DIFFICULTIES[state.route],stage=state.stage;$('#stage-label').textContent=({gate:'00 / SCHOOL GATE',interior:'01 / THE CLASSROOM',stairs:'02 / THE BROKEN STAIRWAY',chase:'03 / RUN TO THE LIGHT'})[stage]||'';$('#location-title').textContent=({gate:state.gate?'세 개의 입구':'잠긴 교문',interior:d.name+' · '+d.label,stairs:'무너진 비상 계단',chase:'마지막 복도'})[stage]||'';$('#objective').textContent=({gate:state.gate?'원하는 난이도의 건물로 걸어가 E를 누르세요.':'교문 앞으로 이동해 E로 잠금장치를 조사하세요.',interior:state.key?'비상 열쇠 획득. 복도 끝 초록색 비상문으로 가세요.':state.notes.length<3?'왼쪽 교실에서 종·달·별 쪽지를 찾으세요. '+state.notes.length+'/3':'칠판의 순서로 숫자를 조합해 복도 끝 보관함을 여세요.',stairs:'푸른 발자국에서 앞으로 이동하며 점프하세요. 세 번 건너면 출구입니다.',chase:'Shift로 달리며 책상을 피하세요. 초록색 출구 앞에서 E!'})[stage]||'';
 $('#inventory').textContent=state.key?'⚿ 비상 열쇠':state.notes.length?'▧ 단서 '+state.notes.length+'/3 · '+state.notes.map(i=>['종','달','별'][i]+': '+d.code[i]).join(' / '):'◇ 소지품 없음';$('#checkpoint').textContent='체크포인트 · '+({gate:'교문',interior:d.name+' 입구',stairs:'계단 시작',chase:'추격 시작'})[state.checkpoint];$('#view-label').textContent=state.third?'3인칭':'1인칭';$('#flashlight-label').textContent=state.light?'☀ 손전등 켜짐':'☾ 손전등 꺼짐';$('#jump-guide').hidden=stage!=='stairs';$('#chase-alert').hidden=stage!=='chase';const steps=['gate','interior','stairs','chase'];$$('#chapter-track span').forEach(el=>{el.classList.toggle('active',el.dataset.step===stage);el.classList.toggle('done',steps.indexOf(el.dataset.step)<steps.indexOf(stage))});campaign?.hud();}
function showModal(type,html,wide=false){campaign?.cancelModal();state.modal=type;state.paused=true;keys={};document.exitPointerLock?.();$('#modal').className=wide?'wide':'';$('#modal').innerHTML=html;$('#modal-backdrop').hidden=false;setTimeout(()=>$('#modal button, #modal input')?.focus(),10);}
function closeModal(){campaign?.cancelModal();state.modal=null;state.paused=false;keys={};$('#modal-backdrop').hidden=true;canvas.focus();}
function openKeypad(kind){const isGate=kind==='gate',length=isGate?4:3;showModal('keypad',`<button class="close" aria-label="닫기" data-close>×</button><div class="modal-eyebrow">${isGate?'THE LOCKED GATE':'EMERGENCY KEY CABINET'}</div><h2 id="modal-title">${isGate?'교문 잠금장치':'비상 열쇠 보관함'}</h2><p>${isGate?'차가운 철문에 숫자 자물쇠가 달려 있다.':'쪽지에서 찾은 숫자를 칠판의 순서대로 입력하세요.'}</p><form id="code-form"><input class="keypad-screen" aria-label="${length}자리 암호" id="code-input" inputmode="numeric" autocomplete="off" maxlength="${length}" pattern="[0-9]*" placeholder="${'—'.repeat(length)}"><div class="keypad">${[1,2,3,4,5,6,7,8,9,'지우기',0,'확인'].map(v=>`<button type="${v==='확인'?'submit':'button'}" data-digit="${v}">${v}</button>`).join('')}</div><div class="code-error" id="code-error" role="status"></div></form><p class="hint">${isGate?'교문 위 문구: “네 번의 종소리 · 4 4 4 4”':'칠판: 종 → 달 → 별<br>주운 쪽지: '+state.notes.map(i=>['종','달','별'][i]+' '+DIFFICULTIES[state.route].code[i]).join(' · ')}</p>`);
 const input=$('#code-input');input.addEventListener('input',()=>input.value=input.value.replace(/\D/g,''));$$('[data-digit]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.digit==='지우기')input.value=input.value.slice(0,-1);else if(b.dataset.digit!=='확인')input.value=(input.value+b.dataset.digit).slice(0,length);input.focus()}));$('#code-form').addEventListener('submit',e=>{e.preventDefault();const code=isGate?'4444':DIFFICULTIES[state.route].code;if(input.value!==code){$('#code-error').textContent='잠금이 풀리지 않습니다. 단서를 다시 확인하세요.';sound(150,.15);return}closeModal();sound(700,.2);if(isGate){state.gate=true;world.remove(world.getObjectByName('gate'));colliders=colliders.filter(c=>c.id!=='gate');interactables=interactables.filter(i=>i.id!=='gate');toast('철문이 열렸습니다. 선택한 코스는 '+DIFFICULTIES[state.route].name+'입니다.');}else{state.key=true;toast('비상 열쇠를 챙겼습니다. 복도 끝 비상문으로 가세요.');}saveProgress();updateHUD();});input.focus();}
function openNote(i,symbol,digit){if(!state.notes.includes(i)){state.notes.push(i);interactables=interactables.filter(o=>o.id!=='note-'+i);const m=world.getObjectByName('note-'+i);if(m)world.remove(m);saveProgress();updateHUD();}sound(560,.13);showModal('note',`<div class="modal-eyebrow">CLUE ${state.notes.length} / 3</div><h2 id="modal-title">${symbol} 그림이 있는 쪽지</h2><div class="note-paper">“${symbol}의 숫자는 <strong>${digit}</strong>.”<br><small>순서는 교실 칠판에 남겨 두었어.<br>열쇠를 찾으면 계단으로 가.</small></div><p>쪽지를 챙겼습니다. 단서는 화면 왼쪽 아래에 기록됩니다.</p><div class="modal-actions"><button class="primary" data-close>계속 탐색하기 →</button></div>`);}
function help(){showModal('help',`<button class="close" aria-label="닫기" data-close>×</button><div class="modal-eyebrow">HOW TO SURVIVE</div><h2 id="modal-title">걸어가고, 살펴보고, 뛰어넘으세요.</h2><div class="help-grid"><kbd>W A S D</kbd><span>앞뒤로 이동 · 좌우로 옆걸음</span><kbd>마우스 / ← →</kbd><span>화면 클릭 후 둘러보기 · 방향키로도 회전</span><kbd>E</kbd><span>가까운 쪽지, 자물쇠, 문 조사</span><kbd>SPACE</kbd><span>점프 · 푸른 발자국에서 앞으로 이동하며 누르기</span><kbd>SHIFT</kbd><span>달리기 · 추격 구간에서는 계속 달리세요</span><kbd>0</kbd><span>1인칭 ↔ 캐릭터가 보이는 3인칭</span><kbd>Q</kbd><span>가까운 적 공격 · 누르고 있으면 연속 공격</span><kbd>J / H</kbd><span>가방과 기억 · 동료의 힌트</span><kbd>F</kbd><span>손전등 켜기 / 끄기</span><kbd>ESC / P</kbd><span>일시정지 · 키 입력이 안 되면 한/영 전환</span></div><p class="hint">모바일: 왼쪽 방향 버튼으로 이동하고 ↶ ↷로 시선을 돌리세요. 오른쪽 조사·점프 버튼을 함께 사용할 수 있습니다.</p><div class="modal-actions"><button class="primary" data-close>알겠어요</button></div>`);}
function pause(){if(!state.running||state.modal)return;showModal('pause',`<div class="modal-eyebrow">TAKE A BREATH</div><h2 id="modal-title">잠깐, 숨을 고르세요.</h2><p>현재 구간의 시작 지점이 저장되어 있습니다.<br>화면을 벗어나거나 멈춘 동안 추격도 멈춥니다.</p><div class="modal-actions"><button class="primary" data-close>계속하기</button><button class="secondary" id="retry-pause">구간 다시 시작</button></div><div class="modal-actions"><button class="secondary" id="home-pause">시작 화면</button><button class="secondary" data-action="help">조작법</button></div>`);$('#retry-pause').onclick=()=>loadStage(state.checkpoint,{retry:true});$('#home-pause').onclick=goHome;}
function fail(reason){if(state.modal||!state.running)return;if(reason==='fall'&&campaign?.fall())return;if(reason==='fall')state.falls++;else state.caught++;saveProgress();sound(reason==='fall'?120:75,state.comfort?.2:.45,state.comfort?.018:.045);if(!state.comfort){$('#hurt').style.opacity='.45';setTimeout(()=>$('#hurt').style.opacity=0,350)}showModal('fail',`<div class="modal-eyebrow">${reason==='fall'?'MISSED THE STEP':'TOO CLOSE'}</div><h2 id="modal-title">${reason==='fall'?'발끝이 닿지 않았어요.':'발소리가 바로 뒤에.'}</h2><p>${reason==='fall'?'푸른 발자국 가까이까지 이동한 뒤, 앞으로 가면서 스페이스바를 짧게 눌러 보세요. 공중에서는 다시 뛸 수 없어요.':'Shift를 누르고 달리세요. 책상에 막히면 A·D로 옆을 피해 가세요. 복도 끝 출구에서 E를 누르면 탈출합니다.'}</p><p class="hint">${reason==='fall'?'점프할 때 W를 계속 누르세요. 달리기 없이도 건널 수 있습니다.':'추격은 복도를 따라 움직입니다. 멈춰 있으면 따라잡힙니다.'}</p><div class="modal-actions"><button class="primary" id="retry">체크포인트에서 재도전 ↗</button><button class="secondary" id="failure-home">시작 화면</button></div>`);$('#retry').onclick=()=>loadStage(state.checkpoint,{retry:true});$('#failure-home').onclick=goHome;}
function win(){if(state.stage==='win')return;if(campaign?.handleWin())return;state.running=false;state.stage='win';write('school-save-v1',null);write('school-save-v2',null);write('school-best-v1',Math.min(read('school-best-v1',Infinity),state.elapsed));sound(600,.5,.05);setTimeout(()=>sound(900,.5,.035),180);showModal('win',`<div class="end-mark">✧</div><div class="modal-eyebrow">CHAPTER COMPLETE</div><h2 id="modal-title">학교 밖의 공기는 따뜻했다.</h2><p>마지막 문이 닫혔다.<br>뒤따르던 발소리도, 더는 들리지 않았다.</p><div class="stat-grid"><div class="stat"><b>${timeLabel(state.elapsed)}</b><small>탈출 시간</small></div><div class="stat"><b>${state.falls+state.caught}</b><small>재도전</small></div><div class="stat"><b>3 / 3</b><small>찾은 단서</small></div></div><p class="hint">${DIFFICULTIES[state.route].name} · ${DIFFICULTIES[state.route].label} 코스를 끝까지 탈출했습니다.</p><div class="modal-actions"><button class="primary" id="replay">다시 탈출하기 ↗</button><button class="secondary" id="end-home">시작 화면</button></div>`);$('#replay').onclick=startNew;$('#end-home').onclick=goHome;}
function customization(){const choices=(key,opts)=>`<div class="segmented">${opts.map(([v,t])=>`<button class="choice ${avatar[key]===v?'chosen':''}" data-option="${key}" data-value="${v}">${t}</button>`).join('')}</div>`;const swatches=(key,values)=>`<div class="segmented">${values.map((v,i)=>`<button class="swatch ${avatar[key]===v?'chosen':''}" style="background:${v}" data-option="${key}" data-value="${v}" aria-label="${key} 색상 ${i+1}"></button>`).join('')}</div>`;
 showModal('custom',`<button class="close" aria-label="닫기" data-close>×</button><div class="modal-eyebrow">MAKE IT YOUR STORY</div><h2 id="modal-title">오늘의 생존자</h2><div class="custom-layout"><div class="avatar-preview">${avatarSVG(avatar)}</div><div class="custom-controls"><div class="option-row full-row"><label for="avatar-name">이름</label><input id="avatar-name" class="story-input" maxlength="16" value="${escapeHTML(avatar.name)}" autocomplete="off"></div><div class="option-row"><label>캐릭터</label>${choices('gender',[['girl','여학생'],['boy','남학생']])}</div><div class="option-row"><label>헤어스타일</label>${choices('style',[['long','긴 머리'],['bob','단발'],['short','숏컷'],['ponytail','포니테일'],['twintail','트윈테일'],['braid','땋은 머리'],['side','옆가르마'],['curly','웨이브']])}</div><div class="option-row"><label>머리색</label>${swatches('hair',['#373044','#594139','#8b6b50','#adb3c5','#815a7e'])}</div><div class="option-row"><label>얼굴형</label>${choices('faceShape',[['soft','부드럽게'],['round','동그랗게'],['tapered','갸름하게']])}</div><div class="option-row"><label>피부색</label>${swatches('skin',['#f3cbb5','#edb99d','#d39b79','#a57155','#79523e'])}</div><div class="option-row"><label>눈동자</label>${swatches('eyes',['#a185c7','#7196b8','#748c69','#9f7353'])}</div><div class="option-row"><label>눈매</label>${choices('eyeShape',[['round','동그랗게'],['sharp','또렷하게']])}</div><div class="small-choices"><div class="option-row"><label>코</label>${choices('nose',[['soft','부드럽게'],['dot','작게']])}</div><div class="option-row"><label>입</label>${choices('mouth',[['smile','미소'],['calm','차분하게']])}</div></div><div class="option-row full-row"><label>의상</label>${choices('outfitType',[['uniform','교복'],['sailor','세일러'],['cardigan','가디건'],['hoodie','후드'],['sport','체육복']])}</div><div class="option-row"><label>옷 색상</label>${swatches('outfit',['#6577ac','#9c728c','#668a86','#8a7c6b'])}</div></div></div><div class="modal-actions"><button class="primary" id="save-avatar">이 캐릭터로 저장 ✧</button></div>`,true);
 $('#avatar-name').oninput=ev=>{avatar.name=safeName(ev.target.value,'수아')};$$('[data-option]').forEach(b=>b.onclick=()=>{avatar[b.dataset.option]=b.dataset.value;const scroll=$('#modal').scrollTop;customization();$('#modal').scrollTop=scroll;});$('#save-avatar').onclick=()=>{write('school-avatar-v1',avatar);closeModal();toast('캐릭터를 저장했어요. 게임에서 0키로 모습을 확인하세요.');};}
function updateInteraction(){let nearest=null,dist=Infinity;for(const item of interactables){const d=Math.hypot(player.x-item.x,player.z-item.z);if(d<item.range&&d<dist){nearest=item;dist=d}}closest=nearest;$('#interaction').hidden=!nearest||!!state.modal;if(nearest)$('#interaction span').textContent=nearest.label;}
function performAction(code){if(code==='Escape'||code==='KeyP'){if(state.modal){if(['pause','help','note','keypad'].includes(state.modal))closeModal();}else pause();return}if(state.modal||!state.running)return;if(code==='KeyQ'){campaign.attack();return}if(code==='KeyJ'){campaign.journal();return}if(code==='KeyH'){campaign.hint();return}if(code==='KeyE'){updateInteraction();closest?.action();}else if(code==='Space'){if(jump(player)){sound(300,.12,.025);if(state.stage==='stairs')state.jumps++;}}else if(code==='Digit0'||code==='Numpad0'){if(campaign.forceThird){toast('전투 중에는 캐릭터가 보이는 3인칭을 유지합니다.');return}state.third=!state.third;updateHUD();toast(state.third?'3인칭 · 캐릭터를 따라가는 시점':'1인칭 · 캐릭터의 시선');}else if(code==='KeyF'){if(campaign.active&&!campaign.hasFlashlight){toast('주변의 예비 손전등을 먼저 주워 주세요.');return}state.light=!state.light;$('#flashlight-label').textContent=state.light?'☀ 손전등 켜짐':'☾ 손전등 꺼짐';sound(600,.035,.015);}}
function updateStairGuide(){const p=stairData.find(p=>player.z<=p.end+.2&&player.z>=p.start-.2);if(p&&p.index<stairData.length-1){const distance=player.z-p.start;const window=campaign?.isStairs?1.05:DIFFICULTIES[state.route].window;$('#jump-cursor').style.left=Math.max(0,Math.min(100,(1-distance/3)*100))+'%';$('#jump-target').style.left=(1-window/3)*100+'%';$('#jump-target').style.width=(window-.08)/3*100+'%';$('#jump-label').textContent=player.grounded?(distance<=window&&distance>.07?'지금! SPACE + 앞으로':'도약 지점까지 '+Math.max(0,distance-window).toFixed(1)+'m'):'점프 중 · 앞으로 계속 이동';}else $('#jump-label').textContent=player.grounded?'계단을 건넜어요. 앞쪽 문으로 가세요.':'공중에서는 앞으로 계속 이동하세요.';
 const landing=stairData.find(p=>player.grounded&&Math.abs(player.y-p.y)<.1&&player.z<p.end&&player.z>p.start);if(landing&&landing.index>0&&landing.index>jumpCounted){jumpCounted=landing.index;toast('착지 성공 · '+landing.index+' / '+(stairData.length-1));sound(700,.1,.025);}}
function updateGhost(dt,t){if(!ghost)return;const last=ghostTrail.at(-1);if(!last||Math.hypot(player.x-last.x,player.z-last.z)>.28)ghostTrail.push({x:player.x,z:player.z});const target=ghostTrail[0];if(target){let dx=target.x-ghost.position.x,dz=target.z-ghost.position.z,dist=Math.hypot(dx,dz),amount=DIFFICULTIES[state.route].ghostSpeed*dt;if(dist<amount){ghost.position.x=target.x;ghost.position.z=target.z;ghostTrail.shift()}else{ghost.position.x+=dx/dist*amount;ghost.position.z+=dz/dist*amount;ghost.rotation.y=Math.atan2(-dx,-dz)}}ghost.position.y=Math.sin(t*2)*.06;const distance=Math.hypot(player.x-ghost.position.x,player.z-ghost.position.z);$('#ghost-distance').textContent=distance.toFixed(1)+'m';if(distance<1.0)fail('caught');if(distance<4&&Math.floor(t*3)!==Math.floor((t-dt)*3))sound(65,.15,.045);}
function updateCamera(t,moving){if(state.stage==='home'){camera.position.set(25+Math.sin(t*.08)*1.2,13.2,30);camera.lookAt(1,4,-5);return}const forward=new THREE.Vector3(-Math.sin(player.yaw),0,-Math.cos(player.yaw));const head=new THREE.Vector3(player.x,player.y+1.63,player.z);const bob=state.comfort?0:(player.grounded&&moving?Math.sin(t*11)*.025:0);head.y+=bob;
 if(state.third){const backward=forward.clone().multiplyScalar(-3.2);const desired=head.clone().add(backward).add(new THREE.Vector3(0,.65,0));let fraction=1;for(let f=.1;f<=1;f+=.08){const xx=head.x+backward.x*f,zz=head.z+backward.z*f;if(colliders.some(b=>xx>b.x-b.w/2-.15&&xx<b.x+b.w/2+.15&&zz>b.z-b.d/2-.15&&zz<b.z+b.d/2+.15&&head.y>b.y-b.h/2&&head.y<b.y+b.h/2)){fraction=Math.max(.06,f-.12);break}}camera.position.copy(head).lerp(desired,fraction);camera.lookAt(head.clone().add(forward.clone().multiplyScalar(4)).add(new THREE.Vector3(0,lookPitch*3,0)));}else{camera.position.copy(head);camera.lookAt(head.clone().add(forward).add(new THREE.Vector3(0,lookPitch,0)));}
 playerModel.visible=state.third;playerModel.position.set(player.x,player.y,player.z);playerModel.rotation.y=player.yaw;const gait=moving&&player.grounded?Math.sin(t*12)*.4:0;playerModel.userData.leftLeg.rotation.x=gait;playerModel.userData.rightLeg.rotation.x=-gait;flash.position.copy(head);flashTarget.position.copy(head).add(forward.multiplyScalar(10)).add(new THREE.Vector3(0,lookPitch*10,0));flash.intensity=state.light?30:0;
}
function animate(now){requestAnimationFrame(animate);const t=now/1000;const dt=Math.min(.04,frameTime?t-frameTime:1/60);frameTime=t;let moving=false;if(state.running&&!state.paused&&!document.hidden){state.elapsed+=dt;saveClock+=dt;if(saveClock>5){saveProgress();saveClock=0}$('#timer').textContent=timeLabel(state.elapsed);player.yaw+=(Number(!!keys.ArrowLeft)-Number(!!keys.ArrowRight))*dt*1.9;controls.forward=Number(!!keys.KeyW)-Number(!!keys.KeyS);controls.side=Number(!!keys.KeyD)-Number(!!keys.KeyA);controls.sprint=!!(keys.ShiftLeft||keys.ShiftRight);moving=!!(controls.forward||controls.side);movePlayer(player,controls,dt,platforms,colliders);campaign?.constrain();if(player.y<-3)fail('fall');if(moving&&player.grounded){stepClock+=dt;if(stepClock>(controls.sprint?.27:.43)){sound(80+Math.random()*25,.05,.012,'triangle');stepClock=0}}updateInteraction();if(state.stage==='stairs'||campaign?.isStairs)updateStairGuide();if(state.stage==='chase')updateGhost(dt,t);}
 campaign?.tick(dt,t);audio.tick();for(const d of decorations){d.m.rotation.y=t;d.m.position.y=d.base+Math.sin(t*2)*.08;}updateCamera(t,moving);renderer.render(scene,camera);}
document.addEventListener('click',e=>{if(e.target.closest('[data-close]'))closeModal();const action=e.target.closest('[data-action]')?.dataset.action;if(action==='help')help();if(action==='sound'){audio.toggle();updateSoundLabels();}if(action==='comfort'){state.comfort=!state.comfort;write('school-comfort',state.comfort);$('#comfort-label').textContent=state.comfort?'켜짐':'꺼짐';toast(state.comfort?'화면 흔들림과 놀람 효과를 줄였어요.':'기본 놀람 효과를 사용합니다.');}});
document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select')){if(e.code==='Escape')closeModal();return}if(['KeyW','KeyA','KeyS','KeyD','ArrowLeft','ArrowRight','Space','KeyE','Digit0','Numpad0','KeyF','KeyQ','KeyJ','KeyH','KeyP','Escape','ShiftLeft','ShiftRight'].includes(e.code)){if(state.running)e.preventDefault();const stageBefore=state.stage;if(!e.repeat)performAction(e.code);if(!state.modal&&state.running&&state.stage===stageBefore)keys[e.code]=true;}});
document.addEventListener('keyup',e=>{keys[e.code]=false});window.addEventListener('blur',()=>{keys={};if(state.running&&!state.modal)pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.running&&!state.modal)pause()});
canvas.tabIndex=0;canvas.addEventListener('pointerdown',e=>{if(state.running&&!state.modal){dragging=true;lastX=e.clientX;lastY=e.clientY;if(e.pointerType==='mouse'){try{canvas.requestPointerLock?.()?.catch?.(()=>{})}catch{}}}});window.addEventListener('pointerup',()=>dragging=false);window.addEventListener('pointermove',e=>{if(!state.running||state.modal)return;if(document.pointerLockElement===canvas){player.yaw-=e.movementX*.0025;lookPitch=Math.max(-.65,Math.min(.6,lookPitch-e.movementY*.002));}else if(dragging){player.yaw-=(e.clientX-lastX)*.005;lookPitch=Math.max(-.65,Math.min(.6,lookPitch-(e.clientY-lastY)*.003));lastX=e.clientX;lastY=e.clientY;}});
document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&state.running&&!state.modal&&document.hasFocus())pause()});
$$('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);const before=state.stage;performAction(b.dataset.key);if(!state.modal&&state.stage===before)keys[b.dataset.key]=true;});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>keys[b.dataset.key]=false)});
function updateSoundLabels(){state.sound=audio.enabled;$$('.sound-label').forEach(el=>el.textContent=audio.enabled?'BGM 켜짐':'BGM 꺼짐');$$('[data-action="sound"]').forEach(el=>el.setAttribute('aria-label',audio.enabled?'BGM 끄기':'BGM 켜기'));}
function damageFlash(){if(state.comfort)return;$('#hurt').style.opacity='.35';setTimeout(()=>$('#hurt').style.opacity=0,220)}
const engine={THREE,state,player,get avatar(){return avatar},get world(){return world},get scene(){return scene},get camera(){return camera},get playerModel(){return playerModel},get keys(){return keys},get colliders(){return colliders},get platforms(){return platforms},audio,box,sphere,cylinder,wall,floorRect,sign,marker,interact,resetScene,createCharacter,createGhost,desk,lamp,loadStage,spawn,showModal,closeModal,saveProgress,goHome,toast,sound,damageFlash,updateSoundLabels,setStairs:v=>{stairData=v},setText:(selector,text)=>{const n=$(selector);if(n&&n.textContent!==text)n.textContent=text}};
campaign=createCampaign(engine);
$('#start').onclick=startNew;$('#continue-game').onclick=continueGame;$('#customize').onclick=customization;$('#pause-button').onclick=pause;$$('[data-route]').forEach(b=>b.onclick=()=>{state.route=b.dataset.route;$$('[data-route]').forEach(el=>el.classList.toggle('selected',el===b));toast(DIFFICULTIES[state.route].name+' 코스를 선택했어요. 교문 너머 해당 건물로 이동하세요.');});$('#comfort-label').textContent=state.comfort?'켜짐':'꺼짐';updateSoundLabels();
for(const type of ['pointerdown','keydown'])document.addEventListener(type,()=>audio.unlock(),{capture:true});
window.addEventListener('error',()=>{if(!renderer||state.modal==='recovery')return;saveProgress();showModal('recovery','<h2 id="modal-title">문제가 발생했습니다.</h2><p>저장된 체크포인트에서 다시 시작할 수 있습니다.</p><div class="modal-actions"><button data-story-home class="primary">메인으로 돌아가기</button><button class="secondary" onclick="location.reload()">새로고침</button></div>')});
await document.fonts.load('700 56px "Noto Sans KR Variable"','학교탈출 본관 급식실 신관 쉬움 보통 어려움 정문 교문 네 번의 종소리 4444 조리 실습실 6학년 4반 단서가 남은 교실 종 달 별 세 기호의 숫자를 순서대로 비상 열쇠 보관함 계단 획득 완료 아직 집에 갈 수 있어 계단실 옥상 연결 복도 오른쪽으로 왼쪽으로 비상구 끝까지 달려');
try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.06,180);buildCourtyard();updateStartButton();requestAnimationFrame(animate);window.addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();saveProgress();showModal('error','<h2 id="modal-title">화면 연결이 잠시 끊겼어요.</h2><p>새로고침하면 마지막 체크포인트에서 이어갈 수 있습니다.</p><div class="modal-actions"><button class="primary" onclick="location.reload()">다시 연결</button></div>');});}catch(e){console.error(e);$('#start').disabled=true;$('#start').insertAdjacentHTML('afterend','<p class="loading-note">3D 화면을 열 수 없습니다. Chrome의 그래픽 가속을 켠 뒤 새로고침해 주세요.</p>');}
// Read-only diagnostics support browser verification; no progression cheats are exposed.
Object.defineProperty(window,'schoolEscape',{value:Object.freeze({snapshot:()=>({stage:state.stage,route:state.route,gate:state.gate,notes:[...state.notes],key:state.key,third:state.third,light:state.light,paused:state.paused,modal:state.modal,elapsed:state.elapsed,falls:state.falls,caught:state.caught,player:{...player},ghost:ghost&&state.stage==='chase'?{x:ghost.position.x,z:ghost.position.z}:null,interaction:closest?.id??null,platforms:stairData.map(p=>({...p})),renderCalls:renderer?.info.render.calls,avatar:{...avatar},story:campaign.snapshot(),audio:audio.snapshot(),interactions:interactables.map(i=>({id:i.id,x:i.x,z:i.z,range:i.range})),colliders:colliders.map(i=>({...i})),playerVisible:playerModel?.visible})})});
