export const STORY_VERSION=2;
export const ART=Object.freeze({roof:'./art/rooftop-student.png',hidden:'./art/hidden-watcher.png',true:'./art/true-reality.png'});
export const STAGES=['easy_hall','easy_cafe','easy_toilet','normal_hall','normal_office','normal_science','hard_entry','hard_english','hard_stairs','hard_math','hard_gym','hard_maze','hard_roof','hard_final'];
export const ROUTE_STATS={easy:{hp:1000,lives:5,damage:50,attack:65,speed:1.1},normal:{hp:500,lives:3,damage:50,attack:65,speed:1.6},hard:{hp:100,lives:3,damage:10,attack:65,speed:6.2}};
export const ITEM_NAMES={flashlight:'손전등',armor:'갑옷',shield:'방패',commonKey:'황동 열쇠',toiletKey:'세면대 열쇠',scienceKey:'과학실 열쇠',organHeart:'심장 표본',organLung:'폐 표본',organLiver:'간 표본',frogPiece:'생명의 조각',chemicalA:'약품 A',chemicalB:'약품 B',resinPiece:'기억의 조각',bonePiece:'동족의 조각',goldenKey:'빛나는 황금 열쇠',blueEnglish:'파란 조각 · 말',blueMath:'파란 조각 · 판단',greenGym:'초록 조각 · 용기',blueRoof:'파란 조각 · 마음',circle:'원형 인장'};
export function escapeHTML(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
export function safeName(v,fallback='이름 없는 학생'){return String(v||'').replace(/[<>\x00-\x1f]/g,'').trim().slice(0,16)||fallback;}
export function freshStory(){return {version:2,active:false,hp:500,maxHp:500,lives:3,armor:100,attack:65,weapon:'수호의 지팡이',items:['flashlight','armor','shield','commonKey'],flags:{},journal:[],dogName:'',friendName:'',friendGender:'boy',mood:'불안하지만 침착함',stairFails:0};}
export function normalizeStory(raw){const d=freshStory();if(!raw||typeof raw!=='object'||Array.isArray(raw))return d;for(const k of ['active'])d[k]=raw[k]===true;for(const k of ['hp','maxHp','lives','armor','attack','stairFails'])if(Number.isFinite(raw[k]))d[k]=Math.max(0,Math.min(k==='hp'||k==='maxHp'?1000:k==='lives'?5:200,raw[k]));d.maxHp=Math.max(1,d.maxHp);d.hp=Math.min(d.hp,d.maxHp);for(const k of ['weapon','mood'])if(typeof raw[k]==='string')d[k]=raw[k].slice(0,50);d.dogName=raw.dogName?safeName(raw.dogName,'모카'):'';d.friendName=raw.friendName?safeName(raw.friendName,'하루'):'';d.friendGender=raw.friendGender==='girl'?'girl':'boy';d.items=Array.isArray(raw.items)?[...new Set(raw.items.filter(i=>Object.hasOwn(ITEM_NAMES,i)))]:d.items;d.flags={};if(raw.flags&&typeof raw.flags==='object')for(const [k,v] of Object.entries(raw.flags))if(/^[a-zA-Z0-9_]+$/.test(k)&&typeof v==='boolean')d.flags[k]=v;d.journal=Array.isArray(raw.journal)?raw.journal.filter(x=>typeof x==='string').map(x=>x.slice(0,400)).slice(-40):[];return d;}
export function normalizeAchievements(raw){return {watcher:raw?.watcher===true,truth:raw?.truth===true,clears:Array.isArray(raw?.clears)?[...new Set(raw.clears.filter(x=>['easy','normal','hard'].includes(x)))]:[]};}
export function readJSON(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
export function writeJSON(key,data){try{localStorage.setItem(key,JSON.stringify(data));return true}catch{return false}}
