import {escapeHTML as h} from './story-state.js?v=2';
import {avatarSVG,DEFAULT_AVATAR} from './avatar.js?v=2';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
export function createStoryUI(e){
 let activity=null;
 function cancel(){activity=null;}
 function dialogue(speaker,lines,choices=[],opts={}){
  const pages=Array.isArray(lines)?lines:[lines];let page=0;let full='';let chars=0;
  const buttons=choices.length?choices:[['계속하기',()=>e.closeModal()]];
  const portrait=opts.portrait||avatarSVG({...DEFAULT_AVATAR,gender:opts.gender||'girl',hair:opts.hair||'#373044',outfit:opts.outfit||'#6577ac'});
  e.showModal('dialogue',`${opts.image?`<div class="story-illustration"><img id="story-image" src="${opts.image}" alt="${h(opts.alt||speaker)}"></div>`:''}<div class="vn-layout ${opts.image?'with-art':''}">${opts.image?'':`<div class="vn-portrait">${portrait}</div>`}<div class="vn-copy"><div class="modal-eyebrow">${h(opts.kicker||'NIGHT OF THE WATCHER')}</div><h2 id="modal-title">${h(speaker)}</h2><p id="vn-text" aria-live="polite"></p><button class="type-skip" id="type-skip">문장 한 번에 보기</button><div id="vn-actions" class="modal-actions"></div><small class="vn-pages" id="vn-pages"></small></div></div>`,true);
  function render(){full=String(pages[page]);chars=opts.instant?full.length:0;$('#vn-text').textContent=full.slice(0,chars);$('#vn-pages').textContent=pages.length>1?`${page+1} / ${pages.length}`:'';const a=$('#vn-actions');a.innerHTML='';const next=page<pages.length-1?[['다음 이야기 →',()=>{page++;render()}]]:buttons;next.forEach(([label,fn],i)=>{const b=document.createElement('button');b.className=i?'secondary':'primary';b.dataset.choice=String(i);b.textContent=label;b.onclick=()=>{if(chars<full.length){chars=full.length;$('#vn-text').textContent=full;return}fn()};a.append(b)});}
  $('#type-skip').onclick=()=>{chars=full.length;$('#vn-text').textContent=full};render();activity={kind:'dialogue',tick:dt=>{if(e.state.modal!=='dialogue')return;if(chars<full.length){chars=Math.min(full.length,chars+dt*43);$('#vn-text').textContent=full.slice(0,Math.floor(chars));}}};
 }
 function mini(kind,title,description,body,seconds,onTimeout){e.showModal('mini',`<div class="modal-eyebrow">HANDS-ON · ${h(kind.toUpperCase())}</div><h2 id="modal-title">${h(title)}</h2><p>${description}</p>${seconds?`<div class="mini-status"><span>남은 시간</span><b id="mini-clock">${seconds.toFixed(1)}</b></div>`:''}${body}<div id="mini-feedback" role="status"></div><button class="mini-cancel" id="mini-cancel">잠시 돌아가기</button>`,true);activity={kind,remaining:seconds,elapsed:0,onTimeout,tick:null};$('#mini-cancel').onclick=()=>e.closeModal();return activity;}
 function done(fn){e.closeModal();fn?.();}
 function cleaning(onWin){let stains=8;mini('cleaning','남겨진 실험 책상','25초 안에 얼룩 8개를 직접 누르거나 문질러 닦으세요.','<div class="clean-desk" id="clean-desk"><span>SCIENCE LAB · 04</span></div><div class="mini-count" id="clean-count">0 / 8</div>',25,()=>retry('청소 시간이 끝났어요.','과학 선생님은 다음 시도를 기다려 줍니다.',()=>cleaning(onWin)));const positions=[[12,21],[37,16],[70,22],[86,49],[55,51],[22,55],[40,79],[72,80]];for(const [i,[x,y]] of positions.entries()){const b=document.createElement('button');b.className='stain';b.dataset.stain=i;b.style.cssText=`left:${x}%;top:${y}%;transform:translate(-50%,-50%) rotate(${i*41}deg)`;b.setAttribute('aria-label',`얼룩 ${i+1} 닦기`);const scrub=()=>{if(!b.isConnected)return;b.remove();stains--;$('#clean-count').textContent=`${8-stains} / 8`;e.sound(800,.055,.025);if(!stains)done(onWin)};b.onpointerdown=ev=>{ev.preventDefault();scrub()};b.onpointerenter=ev=>{if(ev.buttons)scrub()};$('#clean-desk').append(b)}}
 function organs(onWin){let selected=null,placed=[];const organs=[['heart','심장','♥'],['lung','폐','◒'],['liver','간','◖']];mini('restore','개구리의 잃어버린 조각','표본 카드를 고른 뒤 이름이 같은 자리에 놓아 주세요. 직접 찾은 세 표본을 되돌려 줍니다.',`<div class="organ-board"><div class="frog-drawing">개구리 표본<div class="frog-body">${organs.map(([id,name],i)=>`<button data-slot="${id}" style="top:${22+i*25}%">${name}</button>`).join('')}</div></div><div class="organ-cards">${[...organs].reverse().map(([id,name,icon])=>`<button class="organ-card" data-organ="${id}"><b>${icon}</b>${name}</button>`).join('')}</div></div>`,0);$$('[data-organ]').forEach(b=>b.onclick=()=>{selected=b.dataset.organ;$$('[data-organ]').forEach(n=>n.classList.toggle('selected',n===b))});$$('[data-slot]').forEach(b=>b.onclick=()=>{if(!selected)return;if(selected!==b.dataset.slot){$('#mini-feedback').textContent='이 표본의 자리와 이름을 다시 살펴보세요.';return}if(placed.includes(selected))return;placed.push(selected);b.classList.add('filled');b.textContent='✓ '+organs.find(o=>o[0]===selected)[1];$(`[data-organ="${selected}"]`).disabled=true;selected=null;if(placed.length===3)done(onWin)});}
 function paint(onWin){let n=0;mini('disguise','같은 얼굴, 같은 교복','얼굴과 교복의 빛나는 표시를 1 → 4 순서대로 칠하세요.',`<div class="paint-avatar">${avatarSVG({...DEFAULT_AVATAR,skin:'#ddd8c9',outfit:'#303846'})}${[[40,37],[60,37],[50,48],[50,72]].map(([x,y],i)=>`<button data-paint="${i}" style="left:${x}%;top:${y}%">${i+1}</button>`).join('')}</div>`,0);$$('[data-paint]').forEach(b=>b.onclick=()=>{if(+b.dataset.paint!==n){e.toast('빛나는 번호 순서대로 칠해 보세요.');return}b.classList.add('painted');b.textContent='✓';b.disabled=true;n++;if(n===4)done(onWin)});}
 function mix(onWin){let pours=[];const a=mini('alchemy','기억을 굳히는 실험','메모에는 “A와 B를 같은 양으로, 각각 한 번”이라고 쓰여 있습니다.',`<div class="alchemy"><button data-pour="A" class="bottle a">약품 A<br><small>1회 붓기</small></button><div class="mix-bowl" id="mix-bowl">빈 틀</div><button data-pour="B" class="bottle b">약품 B<br><small>1회 붓기</small></button></div>`,0);$$('[data-pour]').forEach(b=>b.onclick=()=>{if(pours.includes(b.dataset.pour))return;pours.push(b.dataset.pour);b.disabled=true;$('#mix-bowl').textContent=pours.length===2?'굳어지는 중…':'절반 채움';$('#mix-bowl').classList.add(pours.length===2?'full':'half');if(pours.length===2){a.elapsed=0;a.tick=()=>{if(a.elapsed>1.6)done(onWin)}}});}
 function english(onWin){const sentences=[['I','am','scared','but','I','will','keep','going'],['We','can','leave','this','school','together']];let round=0;function run(){const target=sentences[round];const order=round===0?[5,1,7,0,6,3,4,2]:[3,5,0,4,2,1];let picked=[];mini('word cards',`영어교실 · ${round+1} / 2`,round===0?'“나는 무섭지만 계속 나아갈 거야.” 순서대로 단어를 골라 문장을 만드세요.':'“우리는 함께 이 학교를 떠날 수 있어.” 단어를 순서대로 골라 주세요.',`<div class="sentence-answer" id="sentence-answer"></div><div class="word-bank">${order.map(i=>`<button data-word="${i}">${target[i]}</button>`).join('')}</div><div class="word-actions"><button id="undo-word" class="secondary">단어 취소</button><button id="reset-words" class="secondary">전체 초기화</button><button id="check-words" class="primary">문장 확인</button></div>`,0);function paint(){const a=$('#sentence-answer');a.innerHTML='';for(const i of picked){const b=document.createElement('span');b.textContent=target[i];a.append(b)}$$('[data-word]').forEach(b=>b.disabled=picked.includes(+b.dataset.word))}$$('[data-word]').forEach(b=>b.onclick=()=>{picked.push(+b.dataset.word);paint()});$('#undo-word').onclick=()=>{picked.pop();paint()};$('#reset-words').onclick=()=>{picked=[];paint()};$('#check-words').onclick=()=>{if(picked.map(i=>target[i]).join(' ')!==target.join(' ')){$('#mini-feedback').textContent='아직 문장이 완성되지 않았어요. 순서를 다시 살펴보세요.';return}round++;if(round<2)run();else done(onWin)};}run();}
 function riddles(onWin){const questions=[['세상에서 가장 시끄러운 물놀이는?','사물놀이'],['아침에는 4발, 점심에는 2발, 저녁에는 3발로 걷는 것은?','사람'],['먹을 수 있는 제비는?','수제비']];let round=0;mini('three heads','케르베로스의 세 질문','세 머리가 동시에 모래시계를 뒤집었습니다. 60초 안에 세 문제를 풀어 주세요.',`<div class="cerberus-heads">◉　◉　◉</div><h3 id="riddle-question"></h3><form id="riddle-form"><input id="riddle-answer" class="story-input" aria-label="수수께끼 답" autocomplete="off" maxlength="30"><button class="primary" type="submit">대답하기</button></form>`,60,()=>retry('모래시계가 멈췄다.','세 머리가 새 모래시계를 준비했다. 다시 도전할 수 있다.',()=>riddles(onWin)));const show=()=>{$('#riddle-question').textContent=`${round+1}. ${questions[round][0]}`;$('#riddle-answer').value='';$('#riddle-answer').focus()};$('#riddle-form').onsubmit=ev=>{ev.preventDefault();if($('#riddle-answer').value.replace(/\s/g,'')!==questions[round][1]){$('#mini-feedback').textContent='다른 머리가 고개를 저었습니다. 다시 생각해 보세요.';return}round++;if(round===3)done(onWin);else show()};show();}
 function survey(onWin){const answers={};mini('survey','체육 선생님의 설문','벽에는 “좋은 기억으로만 문이 열린다”라는 문구가 남아 있습니다.',`<div class="survey">${['오늘 수업은 어땠나요?','친구와 함께하는 활동은요?','다시 만날 내일은요?'].map((q,i)=>`<fieldset><legend>${q}</legend>${['별로','보통','매우 좋음'].map((s,j)=>`<button data-survey="${i}" data-rating="${j}">${s}</button>`).join('')}</fieldset>`).join('')}</div><button id="submit-survey" class="primary">설문 제출</button>`,0);$$('[data-survey]').forEach(b=>b.onclick=()=>{answers[b.dataset.survey]=+b.dataset.rating;$$(`[data-survey="${b.dataset.survey}"]`).forEach(x=>x.classList.toggle('selected',x===b))});$('#submit-survey').onclick=()=>{if(Object.keys(answers).length===3&&Object.values(answers).every(x=>x===2))done(onWin);else $('#mini-feedback').textContent='선생님이 벽에 적힌 문장을 가리켰다. “좋은 기억으로만.”'};}
 function rps(onWin){let chosen='';const a=mini('rhythm','원형 인장을 지켜라','손 모양을 미리 고르세요. 실제로 손을 내는 순간은 구령의 마지막 “보!”입니다.',`<div class="rps-cue" id="rps-cue">안 내면</div><div class="rps-hands">${[['rock','✊','바위'],['scissors','✌','가위'],['paper','✋','보']].map(([id,icon,name])=>`<button data-hand="${id}"><b>${icon}</b>${name}</button>`).join('')}</div>`,0);$$('[data-hand]').forEach(b=>b.onclick=()=>{chosen=b.dataset.hand;$$('[data-hand]').forEach(x=>x.classList.toggle('selected',x===b))});const cues=['안 내면','리셋된다','가위','바위','보!'];let resolved=false;a.tick=()=>{if(resolved)return;$('#rps-cue').textContent=cues[Math.min(4,Math.floor(a.elapsed/.65))];if(a.elapsed>=2.7){resolved=true;$$('[data-hand]').forEach(b=>b.disabled=true);$('#rps-cue').textContent=`상대 ✌  ·  나 ${chosen==='rock'?'✊':chosen==='scissors'?'✌':chosen==='paper'?'✋':'…'}`;a.elapsed=0;a.tick=()=>{if(a.elapsed<1.2)return;if(chosen==='rock')done(onWin);else retry(chosen==='scissors'?'같은 손이 나왔다.':'인장을 놓칠 뻔했다.','상대가 내는 손을 기억하고 한 번 더 도전하세요.',()=>rps(onWin))};}};}
 function finalDoor(onWin){let count=0,started=false;const a=mini('last door','빛 너머로, 함께','첫 두드림부터 10초. 문을 30번 두드리면 곧바로 진엔딩으로 이어집니다.',`<button id="mash-door" class="mash-door"><span>마지막 문 두드리기</span><b id="mash-count">0 / 30</b><i id="mash-progress"></i></button>`,0);const status=document.createElement('div');status.className='mini-status';status.innerHTML='<span>남은 시간</span><b id="mini-clock">10.0</b>';$('#mash-door').before(status);a.remaining=10;a.onTimeout=()=>retry('문을 조금만 더 두드렸더라면.','조각과 동료는 그대로입니다. 마지막 문부터 다시 시도할 수 있어요.',()=>finalDoor(onWin));a.holdTimer=true;$('#mash-door').onclick=()=>{if(!started){started=true;a.holdTimer=false}count++;$('#mash-count').textContent=`${count} / 30`;$('#mash-progress').style.width=(count/30*100)+'%';e.sound(160+count*12,.06,.03);if(count>=30)done(onWin)};}
 function frame(items,onWin){let placed=[];mini('fragments','네 기억이 만나는 액자','각 조각을 눌러 빈 액자에 끼워 주세요. 서로 다른 방에서 찾은 네 기억이 필요합니다.',`<div class="memory-frame">${items.map(([id],i)=>`<div data-frame-slot="${id}">${i+1}</div>`).join('')}</div><div class="fragment-bank">${items.map(([id,name])=>`<button data-fragment="${id}">${name}</button>`).join('')}</div>`,0);$$('[data-fragment]').forEach(b=>b.onclick=()=>{if(placed.includes(b.dataset.fragment))return;placed.push(b.dataset.fragment);b.disabled=true;$$('.memory-frame div')[placed.length-1].classList.add('filled');if(placed.length===items.length)done(onWin)});}
 function retry(title,description,fn){e.showModal('retry-mini',`<div class="modal-eyebrow">TRY AGAIN</div><h2 id="modal-title">${h(title)}</h2><p>${h(description)}</p><div class="modal-actions"><button id="retry-mini" class="primary">다시 도전</button><button data-close class="secondary">방으로 돌아가기</button></div>`);$('#retry-mini').onclick=fn;}
 function tick(dt){const a=activity;if(!a||document.hidden)return;if(a.kind==='dialogue'){a.tick(dt);return}if(e.state.modal!=='mini')return;a.elapsed+=dt;if(a.remaining>0&&!a.holdTimer){a.remaining=Math.max(0,a.remaining-dt);if($('#mini-clock'))$('#mini-clock').textContent=a.remaining.toFixed(1);if(a.remaining===0){const fn=a.onTimeout;activity=null;fn?.();return}}a.tick?.(dt);}
 return {dialogue,cleaning,organs,paint,mix,english,riddles,survey,rps,finalDoor,frame,retry,tick,cancel,snapshot:()=>activity?{kind:activity.kind,remaining:activity.remaining,elapsed:activity.elapsed}:null};
}
